### ISSUE TITLE
Feature request: Progress bar

### ISSUE THREAD

**Issue by lconcha** [daducci/AMICO#1]
Congratulations on the fantastic toolbox. I am amazed by the speed of model fitting for NODDI and, considering that the results can be ready in a short time, I find myself staring at the monitor until I see the [DONE] flag. I have put a text-only progress indicator in AMICO_NODDI.m, but of course subsequent git pull requests overwrite my changes. 

May I suggest dispstat for this purpose:
 (http://www.mathworks.com/matlabcentral/fileexchange/44673-overwritable-message-outputs-to-commandline-window)

but really, any type of text-based progress indicator would do the job.

Thanks again for the great tool.

**Comment by daducci** [comment]
Hi @lconcha, thanks for the suggestion!
Actually, I had tried some time ago to add a progress bar, but I was never able to "go back" by some characters (to update the bar) once I wrote in the output. Do you know how to do it?

Also, I would prefer to avoid any external package, if possible, to make the tool independent from other software/scripts (like in this case).
If you can suggest any way to implement it, I would love to add it straightaway! Or perhaps you can do it and contribute to AMICO! :)

PS: we recently made some modifications to the structure of the framework, for being a bit more modular. In the future, the plan is to implement AMICO in Python in the [dipy](http://nipy.org/dipy/) library as well. With respect to this, I planned to add some additional modification in the next few days to make this transition smoother.

**Comment by lconcha** [comment]
The trick is to repeat an empty string. It is not my idea, I got it from here:
http://undocumentedmatlab.com/blog/command-window-text-manipulation/

I do not feel confident enough with git to actually modify code, but give me a little time...

Cheers,

Luis

**Comment by daducci** [comment]
I implemented the progress bar according to your suggestion (see commit 4e4bfae4fc4f344c56eb6b38d12d162e066e3e1a). I hope this is what you had in mind?

**Comment by lconcha** [comment]
Beautiful, and elegantly coded. Thank you for implementing it so quickly!
