### ISSUE TITLE
Required argument 'n' (pos 3) not found

### ISSUE THREAD

**Issue by ezefarrher** [daducci/AMICO#107]
Hi everyone!
I'm having an error when trying to fit NODDI to any data set (even the example data set from NODDI website) and I'd appreciate it if you could give me a hint. So, all steps run without problems until ae.fit(), where I get the following error:

-> Fitting "NODDI" model to 5478 voxels:
   [                                                  ]   0.0% ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-cb87f2f81d46> in <module>
----> 1 ae.fit()

~/.local/lib/python3.6/site-packages/amico/core.py in fit(self)
    416 
    417                     # dispatch to the right handler for each model
--> 418                     MAPs[ix,iy,iz,:], DIRs[ix,iy,iz,:], x, A = self.model.fit( y, dirs.reshape(-1,3), self.KERNELS, self.get_config('solver_params'), self.htable )
    419 
    420                     # compute fitting error

~/.local/lib/python3.6/site-packages/amico/models.py in fit(self, y, dirs, KERNELS, params, htable)
    647 
    648         # estimate CSF partial volume (and isotropic restriction, if exvivo) and remove from signal
--> 649         x, _ = scipy.optimize.nnls( A, y )
    650         yy = y - x[-1]*A[:,-1]
    651         if self.isExvivo == True :

TypeError: Required argument 'n' (pos 3) not found

I've been reading the forum, but didn't manage to find a solution.

Thanks a lot for your time!

Cheers

**Comment by MarioOcampo** [comment]
Hello @ezefarrher, 
thanks for letting us know about the problem. 

What version of `scipy` do you have (`pip list`)?
The error is generated when the function `scipy.optimize.nnls( A, y )` is executed. 
Could you try to execute that function alone, not necessarily with the same data, to try to reproduce the error? 
Let us know 

Best

**Comment by ezefarrher** [comment]
Hi @MarioOcampo,

thanks for the reply.

I have scipy (1.5.4). Indeed, I tried a very basic example with scipy.optimize.nnls and it also failed.
Fortunately, I managed to solve the problem. Apparently there was an issue with my Anaconda environment. So I uninstalled scipy and installed it again from pip. 

Thanks a lot for the help!

Cheers

**Comment by MarioOcampo** [comment]
It is good to know that the problem is solved.

Best.
