### ISSUE TITLE
generate_kernels

### ISSUE THREAD

**Issue by ezefarrher** [daducci/AMICO#108]
Hi, is it necessary to generate the kernels again, if new subjects are added to the study?
Thanks!

**Comment by MarioOcampo** [comment]
Hello @ezefarrher, 

If they have the same scheme file (or same b-values) there is no need to generate the kernels. 

If the kernels were generated with an old version of AMICO and you are using an updated version now, it may ask you to regenerate the kernels. If this is the case, the default option of kernels is compatible among different versions, but they have to be updated for the new version.   

Best
Mario

**Comment by ezefarrher** [comment]
ok, thank you!
Cheers
