### ISSUE TITLE
Error when resampling kernels ( ae.load_kernels() ) 

### ISSUE THREAD

**Issue by stremblay18** [daducci/AMICO#113]
Hi,

I'm getting the following error when running the ae.load_kernels(). I generated the kernels using another subject, therefore I did not generate it again on the second subject.

At first I thought the problem was due to the slightly different b values between participants (bvals were 5, 995, 2005, so not exactly [0, 1000, 2000, 3000] like they should be). I used the solution proposed here https://github.com/neuralabc/TractREC/blob/master/TractREC/preprocessing.py to "sanitize" the bvals and then create the scheme file with those sanitized bvals. When I load data, I now see what is expected: subjects have the same number of shells (3) and same bvals. I then set the model and load kernels, where I get an error: 

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int' 
(see also screenshot of error below).

This is my code for reference:

## Tell AMICO the location/directory containing all the data for this study
`ae = amico.Evaluation("/data/study/preprocess/", 'ID_subject1')`

## Sanitize bvals as in https://github.com/neuralabc/TractREC/blob/master/TractREC/preprocessing.py
```
def sanitize_bvals(bvals,target_bvals=[0,1000,2000,3000]):
    """
    Remove small variation in bvals and bring them to their closest target bvals
    Returns bvals equal to the set provided in target_bvals 
    """
    for idx,bval in enumerate(bvals):
        bvals[idx]=min(target_bvals, key=lambda x:abs(x-bval))
    return bvals

```
## Read bvals file
```
with open('/data/study/ID_subject1/DWI_unbiased.bvals') as f:
    bvals = f.read()
    bvals = list(map(int, bvals.split()))
    print(bvals)

sanitize_bvals(bvals,target_bvals=[0,1000,2000,3000])
```

## Write new bvals to file
```
with open("/data/study/ID_subject1/DWI_unbiased_sanitized.bvals", 'w') as file:
    s = " ".join(map(str, bvals))
    file.write(s+'\n')
```

## Write scheme file from sanitized bvals
`amico.util.fsl2scheme("/data/study/ID_subject1/DWI_unbiased_sanitized.bvals", "/data/study/ID_subject1/DWI_unbiased.bvecs")`

## Load data
`ae.load_data(dwi_filename = "DWI_unbiased.nii.gz", scheme_filename = "DWI_unbiased_sanitized.scheme", mask_filename = "/data/study/ID_subject1/mask.nii.gz", b0_thr = 0)`

-> Loading data:
	* DWI signal
		- dim    = 145 x 174 x 145 x 288
		- pixdim = 1.250 x 1.250 x 1.250
	* Acquisition scheme
		- 288 samples, 3 shells
		- 18 @ b=0 , 90 @ b=1000.0 , 90 @ b=2000.0 , 90 @ b=3000.0 
	* Binary mask
		- dim    = 145 x 174 x 145
		- pixdim = 1.250 x 1.250 x 1.250
		- voxels = 799670
   [ 15.2 seconds ]

-> Preprocessing:
	* Normalizing to b0... [ min=0.00,  mean=0.15, max=59970.34 ]
	* Keeping all b0 volume(s)
   [ 5.9 seconds ]

## Set NODDI model
`ae.set_model("NODDI")`
## Load the precomputed kernels 
`ae.load_kernels()`

Error:

<img width="1174" alt="Screen Shot 2021-05-25 at 11 57 01 AM" src="https://user-images.githubusercontent.com/52012786/120042469-2173a400-bfd8-11eb-86e5-e936bec6029c.png">
 
I would greatly appreciate any help on this issue.

Best,

Stefanie

**Comment by MarioOcampo** [comment]
Hello @stremblay18 , 
thank you for report the issue. You are right, you do not need to regenerate the kernels for every subject, but you need to call the function `generate_kernels` for each of them to set configurations that will be used in the next steps. By default, the function does not regenerate the kernels, but it can be specified and executed as `ae.generate_kernels(regenerate=False)` before `ae.load_kernels()`.

Let us know if this solved your problem. 
Best
Mario

**Comment by stremblay18** [comment]
Hi,

Thanks a lot for your quick response. It did solve my problem. I did not know I needed to call the ae.generate_kernels function when kernels are already generated.

Best,

Stefanie
