### ISSUE TITLE
ae.fit() SANDI

### ISSUE THREAD

**Issue by surendra116083** [daducci/AMICO#115]
Hello AMICO Community,

I got an issue with ae.fit().

![error](https://user-images.githubusercontent.com/24285775/120938269-d7fc2500-c74c-11eb-9498-ab019614c3b8.JPG)

It says bvals and bvecs should be (N, ) and (N, 3) arrays respectively. However, the same code works for the sample data.

My data consists of the bvals, a single row of 47 columns and the bvecs, three rows of 47 columns respectively.

When I checked the sample data, the bvals were also arranged in a single row multiple columns and bvecs were also structured in three rows multiple columns respectively.  This arrangement is similar to my data. So, I am confused here.

I have attached the screenshot of my error here.

Best Regards,
Suren

**Comment by MarioOcampo** [comment]
Hello @surendra116083, 
thank you for let us know about the issue. 

Can I ask you to check the `scheme` object? Could you execute:
```
ae.scheme.b.shape
ae.scheme.raw.shape
```
what do you obtain? 

Best. 
Mario

**Comment by surendra116083** [comment]
Hello @MarioOcampo Mario,

Thank you very much. The code is working well.

Best,
Suren

**Comment by surendra116083** [comment]
Hello @MarioOcampo Mario,

I was using single-shell data. So, I think I was getting this issue. I am new to AMICO. Apologies.

Best,
Suren

**Comment by MarioOcampo** [comment]
Hello @surendra116083, 
it is OK, do not worry. This problem that you reported will help us to improve the implementation, improving the messages is part of the process. Thank you for letting us know.
It is good to know that the problem is solved.

Best 
Mario
