### ISSUE TITLE
How to speed up NODDI in terminal macOS?

### ISSUE THREAD

**Issue by surendra116083** [daducci/AMICO#119]
Hello @daducci, 

I always appreciate your prompt response to solve my issue. I again ran into an issue. I am using 4 cores MacBook Pro 32 GB RAM. However, the NODDI is taking more than 4 hours to complete the task in the terminal. Would you please suggest to me how can I speed up the task?

Many Thanks,
Suren

**Comment by daducci** [comment]
Dear @surendra116083 ,

did you get any improvement with the suggestion we provided?

Let us know. Best,
Ale

**Comment by surendra116083** [comment]
Dear @daducci ,

Yes, it improved with GPU. Thank you very much.

Regards,
Suren
