### ISSUE TITLE
NODDI for exVivo mouse brain, IC_VFs higher?

### ISSUE THREAD

**Issue by surendra116083** [daducci/AMICO#120]
Hello @daducci ,

My name is Suren from IUPUI, Indianapolis. I am always thankful for your quick response to my brain hacking issues. Recently I was running NODDI for exVivo mouse brain in the macOS terminal. However, IC_VFs are higher. When I checked the code of models.py under Class NODDI(BaseModel), I noticed self.isExvivo=False is initialized. Since my data is exVivo data, I am wondering how can I possibly change self.isExvivo=True.

I am thinking I need to provide additional parameters in this line:
>>> ae.set_model("NODDI")

Many Thanks,
Suren

Many Thanks,
Suren

**Comment by daducci** [comment]
Dear @surendra116083 ,

if you follow the demo, then you should change the followinf part:
```python
ae.set_model("NODDI")
ae.generate_kernels()
```
to
```python
ae.set_model("NODDI")
ae.model.set( <PUT HERE THE PARAMETERS' VALUES YOU WANT> )
ae.generate_kernels()
```
You can find the list of parameter of `ae.model.set()` function here: https://github.com/daducci/AMICO/blob/9fcb61b524b842939a42cb50fc8a46e9f945f869/amico/models.py#L526

**Comment by surendra116083** [comment]
Hello @daducci Professor Alessandro,

Thank you very much. I really appreciate your time, effort, and comments. Actually, I am doing a pair-wise group comparison of diseased and healthy mice brains. I can successfully run NODDI. Yet, the standard deviation in the ROIs is higher, so the ROIs are not statistically significant. Though, the mean values of the ROIs are also visually different in the bar plots. I am wondering high SDs might have happened due to outliers. Would you guide me on when to remove outliers in the image data (in preprocessing or after NODDI results)? Also, I would be grateful if you kindly comment on how to remove outliers as well?

Best Regards,
Suren

**Comment by daducci** [comment]
It depends if outliers are due to noise, poor image registration (so the ROI might be not well defined) etc. In the first case, you could try with denoising your data, whereas in the latter I'd try eroding the ROIs before computing the summary statistics. Or, if you use R for instance, you could try with robust regression models (but I'm not very familiar)
