### ISSUE TITLE
ae.load_data OSerror

### ISSUE THREAD

**Issue by karkantar** [daducci/AMICO#127]
Hi there,

I've been getting the following error when I try and run ae.load_data:

```
Expected 1960200 bytes, got 1959848 bytes from amico_noddi_kk_pilot/Subject01/NODDI_DWI.img
could the file be damaged?
```
I dont believe the file is damaged and I even converted my image from 32bit to 16bit but the error persists. 
My header is 352 bytes and my DWI image is 1,960,200 bytes which adds up to 1959848 bytes but I am only inputting the .img file into the line of code:

`ae.load_data(dwi_filename = "NODDI_DWI.img", scheme_filename = "NODDI_protocol.scheme", mask_filename = "roi_mask.img", b0_thr = 0)`

Any ideas as to what may be happening here? Thanks in advance!

**Comment by daducci** [comment]
Hi @karkantar ,

I've never seen that error, but it seems related to a damaged/corrupted file. Which data is it, is it the demo data that we released? If not, would it be possible for you to share the data with us so that we can internally check what is causing your error?

**Comment by karkantar** [comment]
Hi @daducci, 

Thanks for getting back to me!

It is not the demo data - I have tried running that and it works perfectly fine. I am trying to make it work with my own data.
It appears that there is an issue when I convert the data from **.mif** format in MRtrix3 to **analyze** format (hdr/img) in preparation for the AMICO NODDI analysis. I think that MRtrix outputs my hdr/img files as if they were a single .nii file. Would you recommend a different conversion software? How does your team get your files into an analyze format?

Thank you in advance!

**Comment by daducci** [comment]
MRtrix conversion usually works very well! In general, suggest you use the ".nii" format rather than ".hdr/.img", but I don't think this is the issue you are facing here. I suspect there is some sort of problem during the conversion of your data, but without looking at the data I cannot get why, sorry

**Comment by karkantar** [comment]
So I can run AMICO NODDI with the .nii image? I saw that the example data was in analyze format so that's why I was trying to convert.

**Comment by karkantar** [comment]
When I try to run with the nifti image:

`ae.load_data(dwi_filename = "NODDI_DWI.nii", scheme_filename = "NODDI_protocol.scheme", mask_filename = "roi_mask.img", b0_thr = 0)`

I get this error:


```
 Loading data:
	* DWI signal
		- dim    = 110 x 110 x 81 x 1
		- pixdim = 2.000 x 2.000 x 2.000
	* Acquisition scheme
		- 109 samples, 3 shells
		- 9 @ b=0 , 64 @ b=2000.0 , 29 @ b=1000.0 , 7 @ b=300.0 
[ ERROR ] Scheme does not match with DWI data

An exception has occurred, use %tb to see the full traceback.

SystemExit: 64
```

I have checked my bvals, bvecs, and scheme file and also compared them to the example data and there didnt seem to be any issues.

**Comment by daducci** [comment]
Ah ok, from the log I see that your acquisition scheme says "**109 samples, 3 shells**" but your NIFTI file has only one volume, i.e. "**dim = 110 x 110 x 81 x 1**". Can you see all the 4D volumes with e.g. `mrview`, `fslview` or other viewers?

**Comment by karkantar** [comment]
Thank you for catching that! I re-converted my mif to nifti again and now its a 4D file with all of the volumes and I was able to run the participant through the pipeline! Do you have a recommendation for how to generate numerical values from the images in order to quanitfy the diffusion metrics?

**Comment by daducci** [comment]
What do you mean?

**Comment by karkantar** [comment]
Sorry if I'm unclear - I mean extract a numerical value for each diffusion metric? Since AMICO spits out nifti images. For example, a numerical value for what the intracellular volume fraction is.

**Comment by daducci** [comment]
AMICO saves the model parameters estimated in every voxel, then it's up to you how to use those values. I guess (if I interpret correctly your message) you want to extract average values in different brain regions using a "_Region of Interest Analysis_" approach, e.g. [as described here](http://andysbrainblog.blogspot.com/2012/07/region-of-interest-analysis.html). Is this what you mean?
