### ISSUE TITLE
Zero CSF values in ICVF map

### ISSUE THREAD

**Issue by surendra116083** [daducci/AMICO#128]
Hello @daducci ,
My issue is very fundamental. I am getting zero CSF values in the ICVF map. I am wondering is it okay to have like this?

Many Thanks,
Suren
![Screen Shot 2022-02-03 at 11 57 53 AM](https://user-images.githubusercontent.com/24285775/152390938-d7075e2e-cad3-4eb8-8a97-ce3408e629f3.png)

**Comment by daducci** [comment]
Yes, of course. The ICVF represents, in fact, the Intra-Axonal Volume Fraction and there are no axons in the CSF inside the ventricles.
Best,
Alessandro
