### ISSUE TITLE
[ ERROR ] Problems generating the signal with "datasynth"

### ISSUE THREAD

**Issue by jrf1024** [daducci/AMICO#129]
Hi, Alessandro,

Thank you for this wonderful tool.
I ran NODDI successfully, however, both SANDI and ACTIVEAX failed with the same ERROR (Problems generating the signal with "datasynth") as shown in the picture below. Please help!
Thank you!

Jack

![2022-02-13_14-39-12](https://user-images.githubusercontent.com/29112666/153742172-b5fd7366-721c-40d3-b3e0-e1ffb3353d01.png)
[SANDI_scheme.txt](https://github.com/daducci/AMICO/files/8055086/SANDI_scheme.txt)
[SANDI.py](https://github.com/daducci/AMICO/files/8055102/SANDI.py.txt)

**Comment by jrf1024** [comment]
Hello @daducci Professor Daducci,
Would you please guide me through this issue? or Is there anyone who can help?  Thank you so much for your kind help.

**Comment by daducci** [comment]
Hi @jrf1024 ,

The error is quite generic, but it usually means that `datasynth` is not properly installed.
have you tried looking at this thread? https://github.com/daducci/AMICO/issues/32

**Comment by jrf1024** [comment]
您的邮件已收到。

**Comment by jrf1024** [comment]
@daducci Professor Daducci,
Thanks very much for you reply. I have solved the error by adding 
export MANPATH=/home/user/camino/man:$MANPATH
export PATH=/home/user/camino/bin:$PATH 
to the end of the $HOME/.bashrc file. 

I have another question. The sample data for SANDI model is multi-shell dMRI data with the highest b value up to 12500. However, our data (1st: 3 shell dMRI data with b values of 1000, 2000 and 3000 and 64 directions for each b value;;;;; 2nd: q-space data with a highest b value of 4000 and 129 q samples in total) are quite different. So can our data  be used to Fit the SANDI model? And how to set the below values according to our own dMRI data?

>>> d_is   = 3.0E-3                                 # Intra-soma diffusivity [mm^2/s]
>>> Rs=np.array([1.55555556e-06,3.44444444e-06,4.44444444e-06,5.33333333e-06,6.00000000e-06,6.55555556e-06,8.11111111e-06,9.55555556e-06,1.16666667e-05])                             # Radii of the soma [meters]
>>> d_in=np.array([0.00091667,0.00169444,0.003])    # Intra-neurite diffusivitie(s) [mm^2/s]
>>> d_isos=np.array([0.00036111,0.00163889,0.003])  # Extra-cellular isotropic mean diffusivitie(s) [mm^2/s]

>>> lambda1 = 0         # lambda1 <-- L1 regularization term (MUST be varied according to data)
>>> lambda2 = 5.0E-3    # lambda2 <-- L2 regularization term (MUST be varied according to data)
>>> ae.set_solver( lambda1=lambda1, lambda2=lambda2 )

**Comment by daducci** [comment]
I am not an expert with the SANDI model, but I think you need higher b-value data for it. In any case, I suggest you write directly to Marco (Palombo) and ask him for advices ;-)

**Comment by jrf1024** [comment]
您的邮件已收到。

**Comment by yunfei920406** [comment]
> @daducci Professor Daducci, Thanks very much for you reply. I have solved the error by adding export MANPATH=/home/user/camino/man:$MANPATH export PATH=/home/user/camino/bin:$PATH to the end of the $HOME/.bashrc file.
> 
> I have another question. The sample data for SANDI model is multi-shell dMRI data with the highest b value up to 12500. However, our data (1st: 3 shell dMRI data with b values of 1000, 2000 and 3000 and 64 directions for each b value;;;;; 2nd: q-space data with a highest b value of 4000 and 129 q samples in total) are quite different. So can our data be used to Fit the SANDI model? And how to set the below values according to our own dMRI data?
> 
> > > > d_is   = 3.0E-3                                 # Intra-soma diffusivity [mm^2/s]
> > > > Rs=np.array([1.55555556e-06,3.44444444e-06,4.44444444e-06,5.33333333e-06,6.00000000e-06,6.55555556e-06,8.11111111e-06,9.55555556e-06,1.16666667e-05])                             # Radii of the soma [meters]
> > > > d_in=np.array([0.00091667,0.00169444,0.003])    # Intra-neurite diffusivitie(s) [mm^2/s]
> > > > d_isos=np.array([0.00036111,0.00163889,0.003])  # Extra-cellular isotropic mean diffusivitie(s) [mm^2/s]
> 
> > > > lambda1 = 0         # lambda1 <-- L1 regularization term (MUST be varied according to data)
> > > > lambda2 = 5.0E-3    # lambda2 <-- L2 regularization term (MUST be varied according to data)
> > > > ae.set_solver( lambda1=lambda1, lambda2=lambda2 )

Hi, Can you share me how can you install the Camino and install  "datasyntj?

**Comment by jrf1024** [comment]
您的邮件已收到。

**Comment by jrf1024** [comment]
> > @daducci Professor Daducci, Thanks very much for you reply. I have solved the error by adding export MANPATH=/home/user/camino/man:$MANPATH export PATH=/home/user/camino/bin:$PATH to the end of the $HOME/.bashrc file.
> > I have another question. The sample data for SANDI model is multi-shell dMRI data with the highest b value up to 12500. However, our data (1st: 3 shell dMRI data with b values of 1000, 2000 and 3000 and 64 directions for each b value;;;;; 2nd: q-space data with a highest b value of 4000 and 129 q samples in total) are quite different. So can our data be used to Fit the SANDI model? And how to set the below values according to our own dMRI data?
> > > > > d_is   = 3.0E-3                                 # Intra-soma diffusivity [mm^2/s]
> > > > > Rs=np.array([1.55555556e-06,3.44444444e-06,4.44444444e-06,5.33333333e-06,6.00000000e-06,6.55555556e-06,8.11111111e-06,9.55555556e-06,1.16666667e-05])                             # Radii of the soma [meters]
> > > > > d_in=np.array([0.00091667,0.00169444,0.003])    # Intra-neurite diffusivitie(s) [mm^2/s]
> > > > > d_isos=np.array([0.00036111,0.00163889,0.003])  # Extra-cellular isotropic mean diffusivitie(s) [mm^2/s]
> > 
> > 
> > > > > lambda1 = 0         # lambda1 <-- L1 regularization term (MUST be varied according to data)
> > > > > lambda2 = 5.0E-3    # lambda2 <-- L2 regularization term (MUST be varied according to data)
> > > > > ae.set_solver( lambda1=lambda1, lambda2=lambda2 )
> 
> Hi, Can you share me how can you install the Camino and install "datasyntj?

Please give me your email. I will contact you later.

**Comment by daducci** [comment]
Dear @jrf1024 ,

sorry for not responding but I though you had fixed the problem. You can write me either at the email address that you can find at https://www.di.univr.it/?ent=persona&id=4397 or here and continue the discussion (it may be useful also to others).

**Comment by jrf1024** [comment]
Dear professor @daducci，
   I have solved the problem yet. But professor @yunfei920406 may have the similar questions. So just now I ask him to leave his email to me. I will help him solve his problems. Thanks😊
