### ISSUE TITLE
Is it possible to disable the progress bar?

### ISSUE THREAD

**Issue by mattcieslak** [daducci/AMICO#130]
Hi! I was wondering if there is an easy way to disable the progressbar. I mostly run AMICO non-interactively and end up with very large log files from the progress bars.

thanks in advance!

**Comment by daducci** [comment]
Hi @mattcieslak ,

yes, this is very much feasible and quite easy to achieve. I'll try to give it a shot as soon as I can! ;-)

In case, are you willing to test it (via a PR) before uploading to PYPI?

Cheers,
Ale

**Comment by mattcieslak** [comment]
yes, happily!

**Comment by daducci** [comment]
Fixed by #131
