### ISSUE TITLE
how to create a .scheme1?

### ISSUE THREAD

**Issue by HekatII** [daducci/AMICO#133]
Dear Experts,

I ran NODDI with great success but then failed with ACtiveAX
How can I create a .scheme1 file? 
The tutorial indicates where to download one but not how to create your own.
https://github.com/daducci/AMICO/wiki/Fitting-the-ACTIVEAX-model

Thanks a lot for your help,
Kind regards

michel

**Comment by daducci** [comment]
Hi Michel,

the file format was define by `Camino` (http://camino.cs.ucl.ac.uk), and you can find some useful information here: http://camino.cs.ucl.ac.uk/index.php?n=Docs.SchemeFiles

Best,
Ale
