### ISSUE TITLE
Blocked in Evaluation::Fit

### ISSUE THREAD

**Issue by nilgoyette** [daducci/AMICO#134]
We can see those lines at the end of `Evaluation::Fit`

    if self.get_config('doComputeNRMSE') :
        NRMSE = np.zeros( [self.get_config('dim')[0], self.get_config('dim')[1], self.get_config('dim')[2]], dtype=np.float32 )
        for i in range(totVoxels) :
            NRMSE[ix[i],iy[i],iz[i]] = estimates[i][2]  # Looks about right
        self.RESULTS['NRMSE'] = NRMSE

    if self.get_config('doSaveCorrectedDWI') :
        DWI_corrected = np.zeros(self.niiDWI.shape, dtype=np.float32)
        for i in range(totVoxels):
            DWI_corrected[ix,iy,iz,:] = estimates[i][3]  # HERE! Looks like a bug.
        self.RESULTS['DWI_corrected'] = DWI_corrected

When I run `scil_compute_freewater.py` (from Maxime Descoteaux lab), I get "blocked" in the second loop. It would probably end if I leave it enough time but I'm pretty sure it's a bug. I modified the line to

    DWI_corrected[ix[i], iy[i], iz[i], :] = estimates[i][3]

it's much faster (!) and the results look right.

**Comment by daducci** [comment]
Dear @nilgoyette ,

sorry I didn't receive any notification! I'll have a look at this part of the code asap and will come back to you!

**Comment by daducci** [comment]
Hi @nilgoyette ,

could you git a try to the version on PYPI (1.4.2) and let me know if this solves the problem?

**Comment by nilgoyette** [comment]
Yes, thank you for the quick fix @daducci
