### ISSUE TITLE
Error in the installation of AMICO

### ISSUE THREAD

**Issue by JayChang91** [daducci/AMICO#135]
Dear Experts,

I met a problem when import AMICO in the python 3.10.4 controller on the WSL (Linux Ubuntu 18.04) in Win 10. It also seems something wrong with `nibabel`, but there is nothing wrong with `pip install nibabel`. However, there is no error when installing `nibabel` and `AMICO`, which showed `Successfully installed dmri-amico-1.4.2`. The detailed information is shown as following:

> mr_zyq@DESKTOP-5A2GI5Q:~$ python

Python 3.10.4 (main, Mar 31 2022, 17:01:23) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import amico
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/amico/__init__.py", line 3, in <module>
    from .core import Evaluation, setup
  File "/usr/local/lib/python3.10/site-packages/amico/core.py", line 10, in <module>
    import nibabel
  File "/usr/local/lib/python3.10/site-packages/nibabel/__init__.py", line 40, in <module>
    from . import analyze as ana
  File "/usr/local/lib/python3.10/site-packages/nibabel/analyze.py", line 87, in <module>
    from .volumeutils import (native_code, swapped_code, make_dt_codes,
  File "/usr/local/lib/python3.10/site-packages/nibabel/volumeutils.py", line 22, in <module>
    from .openers import Opener, BZ2File, IndexedGzipFile
  File "/usr/local/lib/python3.10/site-packages/nibabel/openers.py", line 12, in <module>
    from bz2 import BZ2File
  File "/usr/local/lib/python3.10/bz2.py", line 17, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

I also post the installation details of `dmri-amico` and `nibabel` as below:
`mr_zyq@DESKTOP-5A2GI5Q:~$ sudo pip install nibabel
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
WARNING: The directory '/home/mr_zyq/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting nibabel
  Downloading http://mirrors.aliyun.com/pypi/packages/c3/f1/6e31b0287aed62233ec93535ac55554ec5e80c81b772b411e878c9d17179/nibabel-3.2.2-py3-none-any.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 1.1 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/site-packages (from nibabel) (58.1.0)
Collecting numpy>=1.14
  Downloading http://mirrors.aliyun.com/pypi/packages/15/87/4d6bc4e2053a4b517b022746f8e2dae328155a4c723bcad4c7d536febf51/numpy-1.22.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 1.3 MB/s eta 0:00:00
Collecting packaging>=14.3
  Downloading http://mirrors.aliyun.com/pypi/packages/05/8e/8de486cbd03baba4deef4142bd643a3e7bbe954a784dc1bb17142572d127/packaging-21.3-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 KB 31.2 MB/s eta 0:00:00
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading http://mirrors.aliyun.com/pypi/packages/80/c1/23fd82ad3121656b585351aba6c19761926bb0db2ebed9e4ff09a43a3fcc/pyparsing-3.0.7-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.0/98.0 KB 1.5 MB/s eta 0:00:00
Installing collected packages: pyparsing, numpy, packaging, nibabel
Successfully installed nibabel-3.2.2 numpy-1.22.3 packaging-21.3 pyparsing-3.0.7
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
mr_zyq@DESKTOP-5A2GI5Q:~$`

Details of installing `dmri-amico`:
` (tutorial-env) mr_zyq@DESKTOP-5A2GI5Q:~$ pip install dmri-amico
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting dmri-amico
  Using cached http://mirrors.aliyun.com/pypi/packages/4e/87/cfc7c6d065d57a894feef220fee444a331fcf4070c5babf5e3f329a8c8f5/dmri-amico-1.4.2.tar.gz (3.0 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: wheel in ./tutorial-env/lib/python3.10/site-packages (from dmri-amico) (0.37.1)
Requirement already satisfied: numpy>=1.12 in ./tutorial-env/lib/python3.10/site-packages (from dmri-amico) (1.22.3)
Requirement already satisfied: scipy>=1.0 in ./tutorial-env/lib/python3.10/site-packages (from dmri-amico) (1.8.0)
Requirement already satisfied: dipy>=1.0 in ./tutorial-env/lib/python3.10/site-packages (from dmri-amico) (1.5.0)
Requirement already satisfied: spams>=2.6.5.2 in ./tutorial-env/lib/python3.10/site-packages (from dmri-amico) (2.6.5.4)
Requirement already satisfied: tqdm>=4.56.0 in ./tutorial-env/lib/python3.10/site-packages (from dmri-amico) (4.64.0)
Requirement already satisfied: joblib>=1.0.1 in ./tutorial-env/lib/python3.10/site-packages (from dmri-amico) (1.1.0)
Requirement already satisfied: h5py>=2.8.0 in ./tutorial-env/lib/python3.10/site-packages (from dipy>=1.0->dmri-amico) (3.6.0)
Requirement already satisfied: nibabel>=3.0.0 in ./tutorial-env/lib/python3.10/site-packages (from dipy>=1.0->dmri-amico) (3.2.2)
Requirement already satisfied: Pillow>=6.0 in ./tutorial-env/lib/python3.10/site-packages (from spams>=2.6.5.2->dmri-amico) (9.1.0)
Requirement already satisfied: packaging>=14.3 in ./tutorial-env/lib/python3.10/site-packages (from nibabel>=3.0.0->dipy>=1.0->dmri-amico) (21.3)
Requirement already satisfied: setuptools in ./tutorial-env/lib/python3.10/site-packages (from nibabel>=3.0.0->dipy>=1.0->dmri-amico) (58.1.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./tutorial-env/lib/python3.10/site-packages (from packaging>=14.3->nibabel>=3.0.0->dipy>=1.0->dmri-amico) (3.0.7)
Building wheels for collected packages: dmri-amico
  Building wheel for dmri-amico (setup.py) ... done
  Created wheel for dmri-amico: filename=dmri_amico-1.4.2-py3-none-any.whl size=3030105 sha256=4af352281936f0967cd6ab33428f8ed9109086b4aaf438596d532e4f766eb50d
  Stored in directory: /home/mr_zyq/.cache/pip/wheels/08/c5/83/4170750bdbdc769e108b6d92accc2ef0799076e6ab9f267f78
Successfully built dmri-amico
Installing collected packages: dmri-amico
Successfully installed dmri-amico-1.4.2
(tutorial-env) mr_zyq@DESKTOP-5A2GI5Q:~$`

I will appreciate you very much if you can help me to fix this problem. Thank you!

**Comment by daducci** [comment]
Dear @JayChang91 ,

It looks like your linux in WSL is missing the 'bz2' library. Can you try installing it and retry?

Ale

**Comment by JayChang91** [comment]
> 

Thank you for your instant reply. I have changed to Anaconda and it can import bz2 under the enviroment of Anaconda. Finally, it works!
