### ISSUE TITLE
Error: Creating LUT for "SANDI" model: 0.0%[ ERROR ] Problems generating the signal with "datasynth"

### ISSUE THREAD

**Issue by yunfei920406** [daducci/AMICO#138]
Coding Environment: Ubuntu+Python 3.8:
After successful installation of dmri-amico, I tried with the sample data and example codes in tutorial of SANDI, the codes are as follows:

`import amico
amico.core.setup( ndirs=1 )
import numpy as np
import spams

ae = amico.Evaluation(".", ".")
ae.set_config("doDebiasSignal",False)
#ae.set_config( 'DWI-SNR', 30.0 ) <-- if you change to "True" line before
ae.set_config('doDirectionalAverage', True)

delta = 0.020           # time between pulses [s]
small_delta = 0.0055    # pulses duration in [s]
TE = 0.030              # echo time if different from delta+small_delta [s] (optional)
amico.util.sandi2scheme("bvals.bval","bvecs.bvec", delta, small_delta, TE_data=TE, schemeFilename ="SANDI_scheme.txt", bStep=100)

ae.load_data(dwi_filename="MouseData_Slice.nii",scheme_filename="SANDI_scheme.txt",mask_filename="MouseData_Slice_Mask.nii", b0_thr = 10)

ae.set_model("SANDI")
d_is   = 3.0E-3                                 # Intra-soma diffusivity [mm^2/s]
Rs=np.array([1.55555556e-06,3.44444444e-06,4.44444444e-06,5.33333333e-06,6.00000000e-06,6.55555556e-06,8.11111111e-06,9.55555556e-06,1.16666667e-05])                             # Radii of the soma [meters]
d_in=np.array([0.00091667,0.00169444,0.003])    # Intra-neurite diffusivitie(s) [mm^2/s]
d_isos=np.array([0.00036111,0.00163889,0.003])  # Extra-cellular isotropic mean diffusivitie(s) [mm^2/s]

ae.model.set(d_is, Rs, d_in, d_isos)

ae.generate_kernels(regenerate = True,ndirs=1)
ae.load_kernels()
lambda1 = 0         # lambda1 <-- L1 regularization term (MUST be varied according to data)
lambda2 = 5.0E-3    # lambda2 <-- L2 regularization term (MUST be varied according to data)
ae.set_solver( lambda1=lambda1, lambda2=lambda2 )
ae.fit()
`

The error occurs, when `ae.generate_kernels(regenerate = True,ndirs=1)` was execute, the error is:
`ae.generate_kernels(regenerate = True,ndirs=1)
-> Creating LUT for "SANDI" model:
   |                                                           |  0.0%[ ERROR ] Problems generating the signal with "datasynth"
Process finished with exit code 64
`

**Comment by yunfei920406** [comment]
Can any researcher give detailed suggestions or guides on the following statements:

Please follow the corresponding [documentation](http://cmic.cs.ucl.ac.uk/camino//index.php?n=Main.Installation) to install Camino and make sure to include the folder containing the script datasynth in your system path.

**Comment by daducci** [comment]
Dear @yunfei920406 ,

the instructions on how to install CAMINO on Linux can be found at the link that is found in your message, under the section "**3.  Installing on Linux/Unix**". Then, in section "**Step 3: Add Camino binaries and man pages to the path**" you will find how to add `datasynth` to your path. Does't this work for you?

**Comment by nightwnvol** [comment]
Dear @yunfei920406,
we have just released the new version of AMICO on PyPi ([dmri-amico v1.5.0](https://pypi.org/project/dmri-amico/)) which no longer requires you to install the CAMINO toolkit on you system.

Can you try to update AMICO with `pip install --upgrade dmri-amico` and run again the sample code? Now it should work properly.
