### ISSUE TITLE
error in AMICO_LoadData

### ISSUE THREAD

**Issue by Dariodc97** [daducci/AMICO#141]
Hi everyone, 

I'm actually having this issue in the step of the loading of the data. I'm going to report here the errors: 
Error using load_nii_hdr (line 79)
Cannot find file
"/home/ddelcuore/NoddiTutorial/Tutorial/NoddiTutorial/Tutorial/NODDI_DWI.hdr".

Error in load_untouch_nii (line 81)
   [nii.hdr,nii.filetype,nii.fileprefix,nii.machine] = load_nii_hdr(filename);

Error in AMICO_LoadData (line 11)
niiSIGNAL = load_untouch_nii( CONFIG.dwiFilename );

Error in untitled (line 19)
AMICO_LoadData

Do you have any idea of how to solve the issue? 

Thank you, 
Kind Regards.

**Comment by MarioOcampo** [comment]
Hello @Dariodc97,

Thank you for letting us know about the error. 

Could you chek that the path "/home/ddelcuore/NoddiTutorial/Tutorial/NoddiTutorial/Tutorial/" is correct. Maybe "NoddiTutorial/Tutorial/NoddiTutorial/Tutorial" is only "NoddiTutorial/Tutorial/".

In the tutorial the file loaded is "NODDI_DWI.img", do you have that file?

Let us know if these changes solved the issue.
Best 
Mario

**Comment by Dariodc97** [comment]
Hi Mario, 

I actually transferred the NODDI_example_dataset to the folder NoddiTutorial/Tutorial. There I do have the file NODDI_DWI.img. Actually, I reckon that the program is choosing the path itself. 

Maybe I made a mistake related to the AMICO_Setup.m file. In AMICO_data_path, do I have to put the path in which the NODDI_example_dataset folder is? Is it correct? 

Thank you again, 
Cheers. 
Dario.

**Comment by MarioOcampo** [comment]
Hello Dario, 
Yes, if the path is different, the problem can be in the configuration of the paths. 

Are you using the Matlab version? I recommend to use the Python version.

Best regards
Mario

**Comment by daducci** [comment]
Ciao Dario,

indeed the MATLAB version is very outdated and not maintained anymore (I think last commit was 7 years ago), so we strongly suggest you to give the python version a try. What is the problem with the python version? If needed, we could speak one of these days and we can assist you.

Ale

**Comment by Dariodc97** [comment]
Hi everyone, 
I'm trying to use python now as you suggested. 

I actually have a problem in the ae.load_data:

ae.load_data( "NODDI_DWI.img", "NODDI_protocol.scheme", mask_filename="roi_mask.img", b0_thr=0 )

-> Loading data:
	* DWI signal
[ ERROR ] DWI file not found

Here is saying that the file was not found, but actually the file is located in the folder that I called: 

ddelcuore@stromboli:~/NODDI_example_dataset$ ls
brain_mask.hdr  NODDI_DWI.img        NODDI_protocol.scheme  roi_mask.img
brain_mask.img  NODDI_protocol.bval  output
NODDI_DWI.hdr   NODDI_protocol.bvec  roi_mask.hdr

Do you have any idea of how to debug the error? 

Thank you. 
Cheers.
