### ISSUE TITLE
Very long time of ae.fit()

### ISSUE THREAD

**Issue by qiuziru** [daducci/AMICO#142]
Dear Dr Daducci:
I'm trying to start NODDI research using AMICO (python version) approach.  Following the instructions, I was successful in generating the final maps, but time for fitting NODDI model (the last step) is very long. Could you please give me any suggestion?

Loading data: 1.3s
Preprocessing: 0.8s
Resampling LUT: 31.4s
Fitting "NODDI" model to 1915200 voxels (using 56 jobs): 2h25min

Thank you in advance.

**Comment by daducci** [comment]
Can you provide some information about your system (OS, architecture, CPUs etc) and the data (dimensions etc)?
Also, did you use a mask for the fitting? It seems you are fitting a huge number of voxels!
Lastly, did you try reducing the angular resolution with the `ndirs` parameter (https://github.com/daducci/AMICO/wiki/Decreasing-the-angular-resolution-of-the-look-up-tables)?

**Comment by qiuziru** [comment]
Thanks for your early reply! I am using Ubuntu 18.04.6 and python 3.8.8. Dimensions of the image：171 x 225 x 51 x 52 (2b0+25b1000+25b2000). Voxel size of the image: 0.9375 x 0.9375 x 2.99995. I really forgot to add mask. By the why, what is the appropriate nidrs value for my data set?
Lastly, how should I implement batch processing? Can I have multiple subjects under one study?

Thanks a lot!
