### ISSUE TITLE
Loading Data Error

### ISSUE THREAD

**Issue by bertram0611** [daducci/AMICO#155]
Dear experts,

Recently, I want to use AMICO to conduct the NODDI analysis.
I downloaded the example data and tested it.
But the following error was obtained when I loaded the sample data.
Does anyone meet the same error?
How to fix it?

Best,
Lin

####################################################################################
>>> ae.load_data( "NODDI_DWI.img", "NODDI_protocol.scheme", mask_filename="roi_mask.img", b0_thr=0 )

-> Loading data:
	* DWI signal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lincai/.pyenv/versions/anaconda3-2022.05/lib/python3.9/site-packages/amico/core.py", line 131, in load_data
    self.niiDWI_img = self.niiDWI.get_data().astype(np.float32)
  File "/Users/lincai/.local/lib/python3.9/site-packages/nibabel/deprecator.py", line 185, in deprecated_func
    raise error_class(message)
nibabel.deprecator.ExpiredDeprecationError: get_data() is deprecated in favor of get_fdata(), which has a more predictable return type. To obtain get_data() behavior going forward, use numpy.asanyarray(img.dataobj).

* deprecated from version: 3.0
* Raises <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 5.0
>>>

**Comment by nightwnvol** [comment]
Hello @bertram0611,

thank you for reporting us this error. We have just released a new version of AMICO v1.5.4, which should fix the issue you are facing. Please reinstall AMICO or update it with `pip install --upgrade dmri-amico` and let us know if the problem has been solved.

**Comment by bertram0611** [comment]
Hi,

Thank you very much for your quick reply.
It has been solved after updating the AMICO.

However, I have another problem when I loaded my data.
I will post my new issue later on.

Best,
Lin
