### ISSUE TITLE
[ ERROR ] No b0 volume to normalize signal with

### ISSUE THREAD

**Issue by bertram0611** [daducci/AMICO#156]
Dear experts,

My DWI data (data.nii.gz) has no a b0 volume, however, the data has a volume with bvalue=5.
When checking the "bvals" file, I found all b values as follows.
5 5 1490 2995 1495 3005 1500 2990 1495 3005 1490 3000 1490 2985 1500 2985 1500 5 3005 1490 2995 1500 3000 1495 3005 1490 2985 1505 2995 1500 3000 1490 3005 5 1505 2995 1490 2980 1500 2990 1505 3000 1500 2985 1495 2995 1495 3000 1485 5 3005 1500 2990 1505 2995 1495 2985 1490 2995 1500 3000 1500 2985 1495 2985 5 1505 3005 1500 2995 1505 3010 1495 3005 1490 2995 1490 3000 1505 3000 1495 5 2985 1500 2985 1490 2995 1495 2995 1490 2980 1500 3000 1490 3005 1495 2990 1500 3005 200 195 200 495 505 500 500 495 495

When I used HCP preprocessing pipeline to analyze my data, it automatically treated bvalue=5 volumes as b0 volumes.
In addition, all b values in my multi-shell data have approximate values around a certain shell value.
For instance, b= 2980, 3010 ..., which all are round 3000. Please see the following error messages.
In my case, should I manually modify the "bvals" file? Or do you have other alternatives to solve this issue?

Best,
Lin

#############################################################################################
>>> ae.load_data(dwi_filename = DWI_FILE, scheme_filename = 'NODDI_protocol.scheme', mask_filename = DWIMASK_FILE, b0_thr = 0)

-> Loading data:
	* DWI signal
		- dim    = 121 x 145 x 121 x 108
		- pixdim = 1.500 x 1.500 x 1.500
	* Acquisition scheme
		- 108 samples, 18 shells
		- 0 @ b=0 , 7 @ b=5.0 , 13 @ b=1490.0 , 11 @ b=2995.0 , 11 @ b=1495.0 , 10 @ b=3005.0 , 14 @ b=1500.0 , 4 @ b=2990.0 , 9 @ b=3000.0 , 9 @ b=2985.0 , 7 @ b=1505.0 , 2 @ b=2980.0 , 1 @ b=1485.0 , 1 @ b=3010.0 , 2 @ b=200.0 , 1 @ b=195.0 , 3 @ b=495.0 , 1 @ b=505.0 , 2 @ b=500.0 
	* Binary mask
		- dim    = 121 x 145 x 121
		- pixdim = 1.500 x 1.500 x 1.500
		- voxels = 497389
   [ 2.9 seconds ]

-> Preprocessing:
	* Normalizing to b0... [ ERROR ] No b0 volume to normalize signal with

**Comment by daducci** [comment]
Dear @bertram0611 ,

You can easily create a suitable scheme file using the[ `util.fsl2scheme`](https://github.com/daducci/AMICO/blob/8d7596340bc978b0e2cb823bb4557713bebba7a9/amico/util.py#L54) command of AMICO by setting the `bStep` parameter to e.g. 50. This way, the b-values will be rounded to the nearest integer multiple of 50. This should fix your problem.

Let us know if this is the case.

**Comment by bertram0611** [comment]
Dear Prof. Daducci,

Thank you very much for providing this kind advice.
I have already made through all processes using AMICO and obtained NODDI metrics for one of my own data.
AMICO is a really amazing tool, which is so fast and easy to use.

Best wishes,
Lin

**Comment by ElChiriquiski** [comment]
Hello, 
I am having the same issue with no b0 volume to normalize signal. I made the requested changes on the bStep parameter and and I am still getting the error message:


-> Rounding b-values to nearest multiple of 50.0

-> Writing scheme file to [ /Volumes/Data/MRI-Data/DTI_7T/108323/pre/brain/dwi/dwi.scheme ]

-> Loading data:
	* DWI signal
pixdim[1,2,3] should be positive; setting to abs of pixdim values
		- dim    = 173 x 207 x 173 x 143
		- pixdim = 1.050 x 1.050 x 1.050
	* Acquisition scheme
		- 143 samples, 4 shells
		- 0 @ b=0 , 15 @ b=50.0 , 64 @ b=1000.0 , 57 @ b=2000.0 , 7 @ b=1950.0 
	* Binary mask
pixdim[1,2,3] should be positive; setting to abs of pixdim values
		- dim    = 173 x 207 x 173
		- pixdim = 1.050 x 1.050 x 1.050
		- voxels = 1259403
   [ 9.8 seconds ]

-> Preprocessing:
	* Normalizing to b0... [ ERROR ] No b0 volume to normalize signal with

**Comment by dicemt** [comment]
Duplicate. https://github.com/daducci/AMICO/issues/178#issuecomment-1841886730
