### ISSUE TITLE
nibabel get_data() deprecation

### ISSUE THREAD

**Issue by mattcieslak** [daducci/AMICO#160]
Hi! The most recent Nibabel release is throwing an error whenever a .get_data() function is called because they want people using .get_fdata() instead. Would you be open to a PR that changes these calls?

**Comment by daducci** [comment]
Hi Matt,

Yes, we are about to release the version 2.0.0 which also includes this fix, but indeed we could also patch this in 1.x versions. I'll discuss this tomorrow and we will release a patch soon!

**Comment by nightwnvol** [comment]
Hi @mattcieslak,
actually this problem has already been solved in the latest available version (`v1.5.4`). You just need to update AMICO with `pip install -U dmri-amico`.
