### ISSUE TITLE
Error when fitting AMICO

### ISSUE THREAD

**Issue by ilariagabusi** [daducci/AMICO#161]
Hi!
I'm trying to run NODDI with AMICO but it gives me an error when it arrives to the fit.
I attached a screenshot with the error (both using 1 and 8 threads).
Can you help me?
Thank you in advance,
Ilaria

<img width="957" alt="error_fit_AMICO" src="https://user-images.githubusercontent.com/90835565/227953457-0eaf1ba0-3b70-4a6b-91d1-6ed7537d100d.png">
<img width="958" alt="error_fit_AMICO_1thread" src="https://user-images.githubusercontent.com/90835565/227955813-7f5e7a92-dcb5-4a7a-bfa8-83b2b114374a.png">

**Comment by nightwnvol** [comment]
Related to joblib/joblib#812, joblib/joblib#1292
