### ISSUE TITLE
Not getting similar results when fitting AMICO and the NODDItoolbox

### ISSUE THREAD

**Issue by nakulrrraval** [daducci/AMICO#165]
Hello,

I am not getting similar results when I fit the same images with AMICO and the NODDItoolbox. While I understand that they are intrinsically different,  are there specific parameters that I should try to play with? I am fairly new to NODDI and any help will be appreciated.

I have attached the screenshot from the two results specifically ODI.

Here are my parameters:
* DWI signal
		- dim    = 141 x 140 x 80 x 72
		- pixdim = 1.700 x 1.700 x 1.700
	* Acquisition scheme
		- 72 samples, 1 shells
		- 8 @ b=0 , 64 @ b=1000.0 
	* Binary mask
		- dim    = 141 x 140 x 80
		- pixdim = 1.700 x 1.700 x 1.700
		- voxels = 363696 

Thank you. 

![Screenshot 2023-07-21 at 3 24 20 PM](https://github.com/daducci/AMICO/assets/60071871/912b84fe-b97d-42a1-934f-db451057e271)

**Comment by nightwnvol** [comment]
Hi @nakulrrraval,

your data seems to be single-shell (only `b=1000`), but the NODDI model requires at least two shells. I think this could be the reason for your different results.

Similar issue:
- #132

**Comment by nakulrrraval** [comment]
Hi @nightwnvol. Thank you very much for your reply. I did realize the problem and on the verge to fix it.
