### ISSUE TITLE
Infrastructure need for AMICO?

### ISSUE THREAD

**Issue by rosenvic** [daducci/AMICO#167]
Hello, I am new to scripting and to diffusion analyses so my apologies for the fairly basic questions. I have received a script to run AMICO from a collaborator that I intend to adapt for my project needs and I noticed their script uses singularity. My lab has a preference not to introduce the use of virtual machines on our linux computers. Is singularity necessary for running AMICO? If not, are there any steps I need to take to ensure I am able to run AMICO on my linux computer?

**Comment by nightwnvol** [comment]
Hi @rosenvic,

You do not need Singularity to run `AMICO`; you only need to have a Python environment on your linux system. You can install `AMICO` by running `pip install dmri-amico`, and then you can execute your script.

In the [wiki](https://github.com/daducci/AMICO/wiki) you can found the complete installation guide and some tutorials.
