### ISSUE TITLE
AMICO fitting time

### ISSUE THREAD

**Issue by TYoshiura** [daducci/AMICO#17]
Dear Dr Daducci:

I'm a Japanese radiologist trying to start NODDI research using AMICO (matlab version) approach. I'm now working on the sample data set provided at NODDI fitting tutorial. Following the instructions, I was successful in generating the final maps, but time for fitting NODDI model (the last step) is much longer than expected (2 min 15 sec vs. expected 15 sec). Could you please give me any suggestion? I'm using a 12-core workstation.
Thank you in advance.

**Comment by daducci** [comment]
Hi @TYoshiura,

thank you for trying AMICO! Indeed your timing is way too high, you should get a fitting time about 10-15 seconds per slice for the demo dataset. On my laptop it takes 5 minutes for the whole brain, so there must be something misconfigured.

What is the time for the computation/rotation of the kernels ("*Generate the kernels*" section)?

One issue we are aware of, is that MATLAB tends to handle really badly the processing with multiple cores (if not properly configured). Can you please try to start MATLAB as:
```matlab
matlab -singleCompThread
```
and then repeat the processing again?

**Comment by TYoshiura** [comment]
Dear Dr Daducci:

 

Thank you for your immediate reply. I’ll try your suggestion, and report the results via GitHub.

With best regards,

 

Takashi Yoshiura

Kagoshima University

**Comment by TYoshiura** [comment]
Dear Dr Daducci:

 

I’m sorry for the delay in response.

With the multi-thread setting, the calculation time for "Generate the kernels" was 350.9 sec.

With the single-thread setting, it was 324.5 sec, and the fitting time was 21.5 sec!

Please show me what I should do.

Thank you.

**Comment by daducci** [comment]
It seems your "problem" is indeed an issue with MATLAB and multi-threading. We actually don't use any multi-threaded code (in fact the computation of the kernels is almost unchanged in your case) but the library we use for the fitting (i.e. SPAMS) apparently has some troubles with the multi-thread execution  MATLAB.

I personally don't know why this happens, but a "workaround" to solve this issue is indeed to execute MATLAB as you did:
```matlab
matlab -singleCompThread
```
which forces the use of only one computational thread.

In your case it seems to solve the timing issue, as the fitting time now sounds closer to what I have on my laptop, i.e. decreased from 135 s to 21.5 s.

**Comment by kohske** [comment]
I had the similar problem with AMICO-python, CeonOS 6, 48 core workstation.
The workaround was to compile SPAMS without OPENMP binding.

```
$ diff setup.py setup.py~
13,16c13,14
< #cc_flags = ['-fPIC', '-fopenmp']
< cc_flags = ['-fPIC']
< #link_flags = ['-fopenmp', '-s' ]
< link_flags = [ '-s' ]
---
> cc_flags = ['-fPIC', '-fopenmp']
> link_flags = ['-fopenmp', '-s' ]
```

```
$ wget "http://spams-devel.gforge.inria.fr/hitcounter2.php?file=33816/spams-python-v2.5-svn2014-07-04.tar.gz" -O spams-python.tar.gz
$ tar zxvf spams-python.tar.gz
$ cd spams-python
$ # sudo yum -y install blas64-static
$ sudo yum -y install blas
$ sudo yum -y install blas-devel
$ sudo yum -y install lapack
$ sudo yum -y install lapack-devel
$ python setup.py install
```

**Comment by TYoshiura** [comment]
Dear Dr Daducci:

 

Thank you for your kind advice.

The documentation of SPAMS says some setting in compiling won’t allow multi-thread. I’ll play around the SPAMS compilation.

Thanks so much!

**Comment by TYoshiura** [comment]
Dr Takahashi:

 

Thank you for your advice. I’ll try this on my Matlab version. In the SPAMS compile.m file, it is said mex, which I chose, might not allow multi-thread. Do you think compiling with gcc would fix it?

**Comment by dicemt** [comment]
Dear Dr. Yoshiura:

I have compiled SPAMS with mex (Microsoft SDK7.1 for Win and Xcode with Clang for Mac), but that does not slow down the fitting in my environment (MATLAB 2012a-2015b).
So the 'mex' itself does not cause the issue.

Could you confirm that you changed line 34 of SPAMS's compile.m to 'false'?
`use_multithread=false;`
If that was 'false,' it may be the compiler you are using.

As an alternative simple workaround, you can insert
`maxNumCompThreads(1);`
above AMICO_Fit(), instead of executing MATLAB with the argument
`matlab -singleCompThread`

Below AMICO_Fit(),
`maxNumCompThreads('automatic');`
would enable hyperthreading on.

D

**Comment by TYoshiura** [comment]
Dr Matsuyoshi:

 

Thank you for your kind comment. “use_multithread” is set at “true”. There may be something else in the compilation setting…

 

TYoshiura

**Comment by dicemt** [comment]
Dear Dr. Yoshiura:

I am sorry for confusing you.
I meant that use_multithread should be set to 'false' when using mex.

Please set it to 'false' and recompile SPAMS.
`use_multithread=false;`

D

**Comment by TYoshiura** [comment]
Dear Dr Matsuyoshi:

 

Fitting time was reduced to 15 sec. Thank you so much!

Thanks, Dr Daducci and Dr Takahashi!

**Comment by steelec** [comment]
Hi all, I have tested the NODDI reconstruction with the HCP data (python version) and have included the times here. Is this the kind of time that you would be expecting?
In [3]: import spams

In [4]: import amico

In [5]: ae=amico.Evaluation('/data/chamal/projects/steele/working/HCP_CB_DWI/source/dwi','100307')

In [6]: ae.load_data(dwi_filename='data.nii.gz',scheme_filename='sanitised.scheme',mask_filename='nodif_brain_mask.nii.gz',b0_thr=0)

-> Loading data:
	* DWI signal...
		- dim    = 145 x 174 x 145 x 288
		- pixdim = 1.250 x 1.250 x 1.250
	* Acquisition scheme...
		- 288 samples, 3 shells
		- 18 @ b=0 , 90 @ b=1000.0 , 90 @ b=2000.0 , 90 @ b=3000.0
	* Binary mask...
		- dim    = 145 x 174 x 145
		- pixdim = 1.250 x 1.250 x 1.250
		- voxels = 741046
   [ 196.1 seconds ]

In [7]: ae.set_model("NODDI")

In [8]: ae.generate_kernels() #appx 2.5 mins

-> Creating LUT for "NODDI" model:
   [ LUT already computed. Call "generate_kernels( regenerate=True )" to force regeneration. ]

In [9]: ae.load_kernels()

-> Resampling LUT for subject "100307":
   [ 239.9 seconds ]                                           

In [10]: ae.fit()

-> Fitting "NODDI" model to 741046 voxels:
   [ 02h 55m 06s ]                                             

In [11]: ae.save_results()

-> Saving output to "AMICO/NODDI/*":
	- configuration  [OK]
	- FIT_dir.nii.gz  [OK]
	- FIT_ICVF.nii.gz  [OK]
	- FIT_OD.nii.gz  [OK]
	- FIT_ISOVF.nii.gz  [OK]
   [ DONE ]

**Comment by daducci** [comment]
Hi @steelec ,

I have never tested the fit with the HCP data myself. However, comparing your numbers with those reported for the demo, the timing is a bit higher, but likely correct. In the demo, fitting 5478 voxels takes around 9-10 s, which is roughly 1-2 ms/voxel. In your case, it took about 3 hours for 741046, thus 14 ms. This difference might be explained by different factors, for instance using a different computer but, especially, by the fact that the HCP dataset contains 288 measurements/voxel (as compared to 72 in the demo) and this clearly makes the computation longer. Does this makes sense to you?

Best,
Ale

**Comment by steelec** [comment]
That sounds reasonable to me. On a second test I also realised that it was surpassing my physical memory and delving into my virtual (for a total hit of approximately 34GB when testing with ipython (which is not particularly memory efficient to begin with...)). This probably explains a large amount of that time difference. I have another test pending on one of our servers (24 core, 40GB) that I will report back on.

Some of the work that I have done with tractography data generated from the HCP has required that I do computations on a slice-by-slice basis to keep memory down. 

Cheers,
Chris

**Comment by daducci** [comment]
What is the size of the lookup-table created by AMICO? Usually they are not that large. The HCP data is usually around 4 GB, so I cannot see why the memory jumps to 34GB!! Do you think it is because of ipython? I'm not an expert here.. :-P

**Comment by arnaudbore** [comment]
Hi,

In response to #55 (you can close it). Compiling SPAMS helps me to control the number of threads used by SPAMS.

I've got a similar question as @steelec I would like to know if time of processing is normal and if the scheme of 96 shells?? is normal.

Thank you in advance.

-> Writing scheme file to [ /scratch/bore/projects/toad_dev/toad_data/RAMRI_001/10-tensorfsl/dwi.scheme ]

-> Loading data:
        * DWI signal...
                - dim    = 110 x 110 x 56 x 109
                - pixdim = 2.000 x 2.000 x 2.000
        * Acquisition scheme...
                - 109 samples, 96 shells
                - 9 @ b=0 , 1 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 1 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 1 @ b=2000.0 , 1 @ b=300.0 , 1 @ b=2000.
0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 2 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 1 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 1 @ b=2000.0 , 1 @ b=1000.0 , 1 @ 
b=2000.0 , 1 @ b=2000.0 , 1 @ b=300.0 , 1 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 1 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 
, 1 @ b=2000.0 , 1 @ b=1000.0 , 2 @ b=2000.0 , 1 @ b=2000.0 , 1 @ b=300.0 , 1 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 1 @ b=2
000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 1 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 1 @ b=2000.0 , 1 @ b=300.0 , 1 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 1
 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 1 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 2 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 1 @ b=2000.0 , 1 @ b=300
.0 , 1 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 1 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 1 @ b=2000.0 , 2 @ b=1000.0 , 1 @ b=2000.0 , 1 @ b=2000.0 , 1 @
 b=1000.0 , 1 @ b=2000.0 , 1 @ b=2000.0 , 1 @ b=300.0 , 1 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 1 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 1 @ b=2000.0
 , 1 @ b=1000.0 , 1 @ b=2000.0 , 1 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=2000.0 , 1 @ b=300.0 , 1 @ b=2000.0 , 1 @ b=2000.0 , 1 @ b=2000.0 , 1 @ b=1000.0 , 1 @ b=
2000.0 , 1 @ b=2000.0 , 1 @ b=1000.0
        * Binary mask...
                - dim    = 110 x 110 x 56
                - pixdim = 2.000 x 2.000 x 2.000
                - voxels = 145780

-> Preprocessing:
        * Normalizing to b0... [ min=-10745.17,  mean=0.79, max=21516.48 ]
        * Keeping all b0 volume(s)...
   [ 10.2 seconds ]

-> Creating LUT for "NODDI" model:
   [ 7520.5 seconds ]                                          

-> Resampling LUT for subject "10-tensorfsl":
   [ 1467.2 seconds ]  

-> Fitting "NODDI" model to 145780 voxels:
   [ 00h 05m 37s ]                                             

-> Saving output to "AMICO/NODDI/*":
        - configuration  [OK]
        - FIT_dir.nii.gz  [OK]
        - FIT_ICVF.nii.gz  [OK]
        - FIT_OD.nii.gz  [OK]
        - FIT_ISOVF.nii.gz  [OK]
   [ DONE ]

**Comment by daducci** [comment]
No, it looks like your scheme file is recognized as indeed having 96 shells! This way it takes very long to compute the lookup-tables (which, btw, must be really huge!!!). What is your actual protocol?

**Comment by arnaudbore** [comment]
Ok, here are the links to [bvecs](https://box.criugm.qc.ca/f/02416c71c5eb41e08c38/?dl=1) and [bvals](https://box.criugm.qc.ca/f/1ee638eefdad480283f5/?dl=1)

Thank you again for your help

**Comment by arnaudbore** [comment]
Ok, it doesn't come from the scheme computation. The bvals were slightly different so as the scheme. I'm going to fix that it should be way faster.

**Comment by daducci** [comment]
Yes, every different bvalue is then interpreted as a different shell and the rotation in the spherical harmonics space is performed independently. There's no problem per se, just a lot of computation (and space) wasted for no reason.

Have a look at this function that might help you:
https://github.com/daducci/AMICO/blob/f4f516040ff7abb4b4bd7d0f4dde36acf67de432/amico/util.py#L4

This function lets you convert a bval/bvec pair into the proper scheme automatically and you can also round the bvalues using the parameter `bStep`.

**Comment by arnaudbore** [comment]
Thank you very much it works very fast now!
Have good day :+1:
