### ISSUE TITLE
How to obtain other parameter results for NODDI models supported by AMICO?

### ISSUE THREAD

**Issue by enjoy-our-life** [daducci/AMICO#172]
Hi! I have successfully calculated the NODDI model and obtained parameter results such as fit_dir.nii.gz, fit_FWF.nii.gz, fit_NDI.nii.gz, and fit_ODI.nii.gz. Now, I would like to know how to specifically obtain additional parameter results like the Intracellular Volume Fraction (Vic) and Isotropic Volume Fraction (Viso) for the NODDI model in AMICO. Could you please provide guidance or documentation links on how to obtain additional parameter results for the NODDI model in AMICO? Thank you very much for your assistance!

**Comment by enjoy-our-life** [comment]
I wanted to extend my sincere apologies for my recent questions, which may have seemed basic or even foolish. I must admit that I'm not very familiar with some of the concepts.

**Comment by nightwnvol** [comment]
Hi @enjoy-our-life,

no problem at all! Please ask without hesitation if you have other questions.
