### ISSUE TITLE
Publish AMICO to conda-forge?

### ISSUE THREAD

**Issue by pauldmccarthy** [daducci/AMICO#176]
Hi @daducci and @nightwnvol,

I was wondering if you have any interest/objection to publish dmri-amico and dmri-dicelib to [conda-forge](https://conda-forge.org/), to allow them to be installed with `conda` / `mamba`? I have created conda recipes for both packages, and am currently building/publishing them in our internal build system - I would be more than happy to add them to the conda-forge ecosystem if you are interested, and manage their maintenance (and/or add you as maintainers - it is usually a very low-effort role). 

I have already opened a PR to add [spams-cython](https://github.com/getspams/spams-cython/) to conda-forge: https://github.com/conda-forge/staged-recipes/pull/24636

You can see the initial recipes I have set up for dmri-dicelib and dmri-amico at these URLs:

 - https://git.fmrib.ox.ac.uk/fsl/conda/dmri-amico/
 - https://git.fmrib.ox.ac.uk/fsl/conda/dmri-dicelib/

And you can see example build logs for both packages here (for Linux x86-64, and intel/ARM macOS):

 - https://git.fmrib.ox.ac.uk/fsl/conda/dmri-dicelib/-/pipelines/21818
 - https://git.fmrib.ox.ac.uk/fsl/conda/dmri-amico/-/pipelines/21823

You can install these prototype packages into a conda environment with a command such as:

```
mamba create \
 -c https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/development/ \
 -c https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public \
 -c conda-forge \
 -p ./amico.env \
 dmri-amico
```

(if we publish AMICO to conda-forge, specifying the FSL conda channels would not be required).

I'm not sure if AMICO specifically requires OpenBLAS, so am currently building against the netlib LAPACK/BLAS libraries, as this is recommended practice for conda-forge packages (it allows the BLAS/LAPACK implementations to be swapped out without recompilation - you can read more about this [here](https://conda-forge.org/docs/maintainer/knowledge_base.html#blas)). But if AMICO does require OpenBLAS specifically, then the recipe can be adjusted accordingly.

Thanks!

**Comment by pauldmccarthy** [comment]
@nightwnvol great, thanks! I'll get the ball rolling over at [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes/) :)

**Comment by pauldmccarthy** [comment]
xref conda-forge/staged-recipes#24708

**Comment by nightwnvol** [comment]
* https://github.com/conda-forge/staged-recipes/pull/24708
