### ISSUE TITLE
Processing: [ ERROR ] no b0 volume with bStep change

### ISSUE THREAD

**Issue by ElChiriquiski** [daducci/AMICO#178]
Hello, 
I am getting an error during preprocessing. When it is normalizing to b0, I get an error saying: No b0 volume to normalize signal with.

I made the requested changes to the bStep and I am still getting the b0 error. 

 NODDI post-processing using AMICO 

-> Rounding b-values to nearest multiple of 2.0

-> Writing scheme file to [ /Volumes/Data/MRI-Data/DTI_7T/100610/pre/brain/dwi/dwi.scheme ]

-> Loading data:
	* DWI signal
pixdim[1,2,3] should be positive; setting to abs of pixdim values
		- dim    = 173 x 207 x 173 x 143
		- pixdim = 1.050 x 1.050 x 1.050
	* Acquisition scheme
		- 143 samples, 26 shells
		- 0 @ b=0 , 6 @ b=64.0 , 7 @ b=980.0 , 3 @ b=1980.0 , 7 @ b=990.0 , 8 @ b=2020.0 , 7 @ b=1010.0 , 8 @ b=1984.0 , 7 @ b=1000.0 , 3 @ b=2024.0 , 2 @ b=976.0 , 7 @ b=60.0 , 4 @ b=2000.0 , 4 @ b=1990.0 , 6 @ b=1016.0 , 8 @ b=2016.0 , 2 @ b=56.0 , 7 @ b=996.0 , 5 @ b=2004.0 , 4 @ b=1970.0 , 6 @ b=1996.0 , 4 @ b=2010.0 , 10 @ b=984.0 , 2 @ b=1964.0 , 8 @ b=1004.0 , 3 @ b=1020.0 , 5 @ b=1976.0 
	* Binary mask
pixdim[1,2,3] should be positive; setting to abs of pixdim values
		- dim    = 173 x 207 x 173
		- pixdim = 1.050 x 1.050 x 1.050
		- voxels = 1351915
   [ 10.4 seconds ]

-> Preprocessing:
	* Normalizing to b0... [ ERROR ] No b0 volume to normalize signal wit
----

Dear @bertram0611 ,

You can easily create a suitable scheme file using the[ `util.fsl2scheme`](https://github.com/daducci/AMICO/blob/8d7596340bc978b0e2cb823bb4557713bebba7a9/amico/util.py#L54) command of AMICO by setting the `bStep` parameter to e.g. 50. This way, the b-values will be rounded to the nearest integer multiple of 50. This should fix your problem.

Let us know if this is the case.

_Originally posted by @daducci in https://github.com/daducci/AMICO/issues/156#issuecomment-1432766131_

**Comment by dicemt** [comment]
You seemed not to have b0 volume. The output indicates that the lowest b-value is around 64 in your data.
Although I feel 64 is somewhat high to consider as b0 volume, you might want to set the `bStep` parameter to e.g. 200.

**Comment by ElChiriquiski** [comment]
Hello,
I was able to get some output added 200 as bStep, but it was not usable. I think I will ask for b0 and merge them to the dwi file and troubleshoot again.

Thank you for your help!

I will make sure to provide an update.

**Comment by ElChiriquiski** [comment]
Hello I received this information regarding our DWI:
_The contents of the bval and bvec files are an accurate representation of the data.
The bvals vary a little bit around each shell (e.g., 5 rather than 0; 1995 and 2005 rather than just 2000) because Siemens takes into account the impact of the imaging-related gradients on its provided diffusion tensor.  Similarly, even the “b=0” data has a “diffusion direction” associated with it.
 The contents of the bval and bvec should be in sync._ 

![image](https://github.com/daducci/AMICO/assets/106636273/8e32400f-28b0-4dbf-9f23-e5724889048d)

@dicemt We were wondering if there was a work around for the program to recognize the b0s. 

Best regards,
Daniel S.

**Comment by dicemt** [comment]
As I said in the earlier post, your lowest b-value is high to **consider as** b0. There is no workaround at this analysis phase but to acquire new DWIs with appropriate MPG profiles.
You can choose Siemens's default "MDDW" diffusion mode and set the desired number of diffusion gradient directions and b-values.

**Comment by ElChiriquiski** [comment]
Dear @daducci ,
Thank you for your input and suggestions regarding this issue, and I apologize for the delay in response. 

As suggested, I was able to create a Python script to edit the bvals to nearest the 0 and thousand. 
![image](https://github.com/daducci/AMICO/assets/106636273/8051607b-4f79-47d1-8f4d-24ac0330c686)

I then ran the script with success:

<img width="649" alt="image" src="https://github.com/daducci/AMICO/assets/106636273/2b029fd7-9ae0-4f1b-898d-df7843363405">

When I took a look at the ICVF output, it appears there is black dots scattered around the image, and we were wondering if there is another change needed, e.g., to bvecs. Please see image below:

![image](https://github.com/daducci/AMICO/assets/106636273/806f7bc5-8aad-4f21-b593-3763415893ae)

Thank you @daducci and @dicemt for your continued support!

**Comment by ElChiriquiski** [comment]
Hello, I want to thank you all for your help once again. I talked to my mentors and they told me the black dots have to deal with the resolution of the images along with micromovements. I want to share the python script I used to process the bvals.


single instance processing that can be converted to batch processing:


import numpy as np

# Provide the path to your dwi.bval file
file_path = '/Volumes/Data1/MRI-Data/DTI_7T/100610/pre/brain/dwi/dwi.bval'

# Read the content of the file
with open(file_path, 'r') as file:
    bvals_data = file.read()

# Split the string into a list of integers
bvals_list = list(map(int, bvals_data.split()))

# Convert the list to a NumPy array
bvals_array = np.array(bvals_list)

# Print the resulting NumPy array
print(bvals_array)


# Round each b-value to the nearest thousand
rounded_shells = np.round(np.array(bvals_list) / 1000) * 1000

# Round the numbers to whole numbers
rounded_shells = np.round(rounded_shells, decimals=0)

# Convert the NumPy array to a Python list and cast to int
rounded_shells_list = [int(shell) for shell in rounded_shells]

# Print the mapping of b-values to rounded shells
for bval, shell in zip(bvals_list, rounded_shells_list):
    print(f"B-value: {bval} -> Rounded Shell: {shell}")
    
# Access the result as a list (rounded_shells_list)
print("Rounded Shells as a Python list:", rounded_shells_list)

# Provide the path to save the dwi.bvals file
output_file_path = '/Volumes/Data1/MRI-Data/DTI_7T/100610/pre/brain/dwi/dwi.bval'

# Write the rounded_shells_list to the new file
with open(output_file_path, 'w') as output_file:
    for shell in rounded_shells_list:
        output_file.write(str(shell) + ' ')
