### ISSUE TITLE
Black output MATLAB

### ISSUE THREAD

**Issue by emilljungberg** [daducci/AMICO#18]
Hi, I am a new user of AMICO for analysis of NODDI data that I am acquiring. As far as I can see, I have successfully installed all dependencies and the whole analysis pipeline runs smoothly in MATLAB with no errors. However, when I look at the output, only the *_DIR image has any content, all the others are completely black with 0s everywhere. I get that there is some dependency issue going on here but since I don't get any errors during the fitting, I am unsure of where to start troubleshooting. 

Do you have any suggestions for how to troubleshoot this? Can I verify the scripts from the SPAMS installation in some way perhaps? I have tried my own data and the sample data set provided here but with no success so far. 

All help is greatly appreciated. Thanks a lot for making this tool available open source and putting up such a great tutorial, it is very appreciated!

Best
Emil Ljungberg
Medical Physics, University of British Columbia.

**Comment by daducci** [comment]
Hi Emil,

usually, when the output is blank as you experienced, it's something to do with the installation of the SPAMS library. Did you run the test scripts located in the `test_release` folder from the MATLAB command line?

**Comment by emilljungberg** [comment]
Thank you! The issue turned our to be that I hadn't set `setenv('MKL_NUM_THREADS','1')` as mentioned on the SPAMS website. `test_release` passed all way through and I now get the correct results from the NODDI analysis as well. Thanks!
