### ISSUE TITLE
NODDI in the infant brain; optimal diffusivity changes

### ISSUE THREAD

**Issue by kjobson-neuro** [daducci/AMICO#180]
Dear experts,

I have recently become interested in implementing NODDI in an infant sample. [This paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0217118) showed that an optimal diffusivity for white matter in infants would be between 1.4e-3 and 1.5e-3, whereas in the grey matter it would be 1.2e-3 to 1.3e-3.

I read the previous thread by mblesac, and wanted to know if my approach to using these new parameters is a) warranted and b) implemented correctly. As there is a range between the white and grey matter, I was going to repeat the fit over this range of values to estimate which one is best for each subject:

```python
import amico
AMICO = amico.Evaluation( ... )
...
AMICO.set_model('NODDI')
for dPar in [ 1.2e-3, 1.3e-3, 1.4e-3 1.5e-3]:
    AMICO.model.set( dPar, ... )
    AMICO.generate_kernels( ... )
    ...
    AMICO.fit()
    AMICO.save_results( path_suffix=f'_dPar={dPar:.2e}' )
``` 
Is this something that would be acceptable? I was also considering getting the fit for the white and grey matter separately. However, I worry about the lack of accurate white and grey matter segmentation in infants, and how complicated this may make my analysis.

I would be very grateful for any insights you can provide. I deeply appreciate the work done here; it has made my life significantly easier in regards to getting NODDI data!

**Comment by daducci** [comment]
Dear Katie,

Your approach looks reasonable and sound, and indeed implemented correctly! The tricky point is, in case, how you choose between the maps estimated with different `dPar` values. Besides, I would not fit separately for WM and GM, but I would do a single fit for both so that you have maps for all possible `dPar` values and later you can decide.

Best,
Ale

**Comment by kjobson-neuro** [comment]
Thank you so much! I appreciate you taking the time to answer my question. I was able to successfully implement this (with the help of mblesac, actually). I wanted to include my code below so those who may want to replicate this have a working script to use.

```python
import amico
ae = amico.Evaluation( ... )
...
ae.set_model('NODDI')
dIso = 3.0E-3
IC_VFs = np.linspace(0.1,0.99,12)
IC_ODs = np.hstack((np.array([0.03, 0.06]),np.linspace(0.09,0.99,10)))
isExvivo = False

for dPar in [ 1.2e-3, 1.3e-3, 1.4e-3, 1.5e-3]:
     ae.model.set( dPar, dIso, IC_VFs, IC_ODs, isExvivo)
     ae.generate_kernels(regenerate=True)
     ae.load_kernels()
     ae.fit()
     ae.save_results( path_suffix=f'_dPar={dPar:.2e}' )
```
