### ISSUE TITLE
v2.0.1 Installation from source fails

### ISSUE THREAD

**Issue by ccoulombe** [daducci/AMICO#181]
Version: 2.0.1
From source, on PyPI
Command : `pip download/install --no-binary`

When installing from source,it fails since the setup expect a file `site.cfg` which obviously do not exists at this point.
```bash
  Running command Preparing metadata (pyproject.toml)
  FileNotFoundError: cannot find the site.cfg file
```

A solution would be to not use a configuration file and instead use variable or environnement variables.

**Comment by nightwnvol** [comment]
Hi @ccoulombe,

thanks for your suggestion! We will consider introducing some environment variables to handle this in future versions.

For now, to install `AMICO` from source please refer to [this documentation page](https://github.com/daducci/AMICO/wiki/How-to-install-AMICO#install-from-source).
