### ISSUE TITLE
Noticeable steps (lack of smoothness) in ICVF/ODI

### ISSUE THREAD

**Issue by AbAstris** [daducci/AMICO#183]
Apologies if this has already been answered, I hadn't seen another thread on this.

I'm new to NODDI, but I have been running AMICO NODDI to speed up the process on paediatric healthy controls (ages 7-17 yrs) and paediatric patients with tumours in the cerebellum/brain stem. One thing I've noticed is that the ICVF image in particular seems to have noticeable steps in the data and looks slightly artificial, i.e. there aren't smooth transitions between voxels nor is there a lot of variation between voxel values.

Here is an example (values set at min 0.2 to max 0.8):

<img width="1269" alt="Screenshot 2024-04-03 at 11 20 37" src="https://github.com/daducci/AMICO/assets/110300778/0a1baa9f-69eb-42bc-96ff-f86e5bec4137">

The ODI map seems better, but there are still areas where multiple voxels have values at 0.3 (i.e. in the corpus callosum). Here is an example (values set at min -0.1 to max 0.9):

<img width="1384" alt="Screenshot 2024-04-03 at 11 31 01" src="https://github.com/daducci/AMICO/assets/110300778/8e9eb61a-d635-47f4-ac94-4c678fe38815">

Here is an example of the python code that I use to run the model:

```
import_ amico

ae = amico.Evaluation("Study01", "Subject03")
amico.util.fsl2scheme("/dir/Study01/Subject19/NODDI_protocol.bvals", "/dir/Study01/Subject19/NODDI_protocol.bvecs")
ae.load_data(dwi_filename="/dir/Study01/Subject19/NODDI_DWI.nii.gz", scheme_filename="/dir/Study01/Subject19/NODDI_protocol.scheme", mask_filename="/dir/Study01/Subject19/brain_mask.nii.gz", b0_thr=0)

ae.set_model("NODDI")
ae.generate_kernels(regenerate=True)
ae.load_kernels()
ae.fit()
ae.save_results()
```

Do these results seem correct or is there something I'm doing wrong?

Best wishes,

Emily

**Comment by AbAstris** [comment]
Hi @daducci,

Thank you for your quick response! I really appreciate it. 

I was more referring to blocks of grey voxels with the same value (not on the edge of the brain). As an example, if I focus on the axial slice of the ICVF map, there are large areas where the values are all the same (this is also found in the coronal and sagittal slices).

![Steps](https://github.com/daducci/AMICO/assets/110300778/823e87e9-3b91-4a26-845f-5c8a1ce8e5ce)

I've circled some of the areas in the above image - the red circle corresponds to a cluster of voxels with the same value of 0.42363637 and the blue circle corresponds to a cluster of voxels with the same value at 0.34272727. 

I also ran the original version of NODDI on MATLAB for comparison - below, on the left is the MATLAB version of NODDI and on the right is the AMICO version of NODDI. The MATLAB version doesn't have clusters of voxels with the same values.

[Comparison_NODDIM_Amico.pdf](https://github.com/daducci/AMICO/files/14866397/Comparison_NODDIM_Amico.pdf)

I just wanted to check to see if this was expected from the AMICO version of NODDI?

**Comment by AbAstris** [comment]
Thank you @daducci. I've now sent you an email.

**Comment by AbAstris** [comment]
To close this issue (just in case anyone else runs into the problem), the solution was to increase the `lambda2` parameter in `set_solver(...)` before the fit. 

For example:
`ae = amico.Evaluation("StudyXX", "SubjectXX")`
`ae.set_solver(lambda1=5e-1, lambda2=1e-2)`

The default values for NODDI: lambda1 = 5e-1, lambda2 = 1e-3

Best wishes and thank you!

**Comment by mblesac** [comment]
Hi,

I'm facing the same issue but much more accentuated as I'm using neonatal data:

![Image](https://github.com/user-attachments/assets/2cdd6ae8-55d1-4fbb-822c-d1bcc8876ffb)

It looks very flat (with ae.set_solver(lambda1=5e-1, lambda2=1e-2))

Any advise about how to modify the parameters? Thanks in advance!

Best regards
