### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by arnaudbore** [daducci/AMICO#187]
Hello !
Are you going to release v2.0.2 and push it to pypi soon ?
Thank you in advance

**Comment by nightwnvol** [comment]
Hi @arnaudbore!
Yes, we are about to release `v2.0.2` and deploy it to PyPI. This version will include precompiled wheels for Python 3.12.

**Comment by arnaudbore** [comment]
Thank you @nightwnvol 
Do you have any timeline ? :wink:

**Comment by nightwnvol** [comment]
@arnaudbore
We expect to have `v2.0.2` available on PyPI by the end of this month.

**Comment by nightwnvol** [comment]
Hi @arnaudbore,
we just released the new version of `dmri-amico` on PyPI. The new version is `v2.0.3` (not `v2.0.2` mentioned above).
