### ISSUE TITLE
Changing the NODDI parallel diffusivity in AMICO v2.0.0

### ISSUE THREAD

**Issue by minisagan** [daducci/AMICO#188]
Hi, 

I was previously able to update the NODDI parallel diffusivity by editing the models.py script, however, this file is no longer present in  lib/python3.9/site-packages/amico after installing  v2.0.0. 

In a previous issue, it was mentioned that the model parameters could be updated via AMICO.model.set( dPar, ... ), but I am not entirely sure which parameters this will update and want to avoid changing the wrong thing.

How should I proceed? 

Kind regards,

Saga

**Comment by daducci** [comment]
Dear Saga,

No need to modify the core code, you can simply change the model parameters via the `set()` function of the model itself, something like the following snippet:

```python
ae = amico.Evaluation()
...
...
ae.set_model('NODDI')
dPar = 1.7E-3 # --- THIS IS THE PARALLEL DIFFUSIVITY YOU WANT TO CHANGE ---
dIso  = 3.0E-3
IC_VFs    = np.linspace(0.1,0.99,12)
IC_ODs    = np.hstack((np.array([0.03, 0.06]),np.linspace(0.09,0.99,10)))
isExvivo  = False
ae.model.set(dPar, dIso, IC_VFs, IC_ODs, isExvivo)
ae.generate_kernels(regenerate=True)
...
...
```

Hope this helps you!
