### ISSUE TITLE
Docker-specific error

### ISSUE THREAD

**Issue by ElChiriquiski** [daducci/AMICO#193]
Hello, 
I am running the same code on the same data inside and outside a docker container using terminal. Only on docker do I get the following error message. I do not get the error when I run from my linux user.

INSIDE DOCKER ERROR:

-> Resampling LUT for subject "/home/danielsalinas/MRI-Data/Francis_HION/NCANDA/practice/NCANDA_S00043/pre/brain/dwi":
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/danielsalinas/miniconda/envs/MRIenv/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/danielsalinas/miniconda/envs/MRIenv/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/danielsalinas/miniconda/envs/MRIenv/lib/python3.6/site-packages/dicelib/ui.py", line 347, in _animate
    print(f"\r   {self._graphics['magenta']}{'\u2501' * int(self.ncols * self._progress / self.total)}{self._graphics['bright_black']}{'\u2501' * (self.ncols - int(self.ncols * self._progress / self.total))} {self._graphics['green']}{100 * self._progress / self.total:.1f}% {self._graphics['cyan']}{self._eta}{self._graphics['reset']}", end='', flush=True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-106: ordinal not in range(128)

**Comment by nightwnvol** [comment]
Hi @ElChiriquiski,

I think your issue is due to the default encoding settings in your Docker container environment. I found a [similar issue](https://github.com/python-poetry/poetry/issues/3672) and they solved it by setting the `PYTHONIOENCODING=utf-8` environment variable in the Dockerfile (or you can set it directly in your `docker run` command).

**Comment by ElChiriquiski** [comment]
Hello @nightwnvol 

Thank you! that fixed the problem I was having. I set it in the docker run command

Greatly appreciate your time,
Daniel Salinas
