### ISSUE TITLE
NODDI returns NaN values

### ISSUE THREAD

**Issue by pkgandhi** [daducci/AMICO#24]
Hello Daducci,

We ran AMICO-NODDI on our data at two different systems - one locally and one on supercomputer. However the results on supercomputer return NaN value for the same data. Is there a way to troubleshoot it? We also tried comparing few matrices and we did not find any differences per say. Any help would be appreciated!

Thanks!

**Comment by daducci** [comment]
Dear @pkgandhi ,

usually when AMICO returns NaN in the maps is because of a bad installation of the SPAMS libraries. Can you please run the tests that you find in its `test_release` folder?

Also check issue #18 for a similar problem that might explain your NaN.

Best,
Alessandro

**Comment by pkgandhi** [comment]
Thank you so much for your reply! Looks like that worked! :+1:
