### ISSUE TITLE
[HELP WANTED] ActiveAx with 2D qspace sampling

### ISSUE THREAD

**Issue by TomMingasson** [daducci/AMICO#27]
Hi,

I'm from NeuroPoly (University Polytechnique of Montreal).
I'm doing spinal cord microstructure parameters estimation.

I would like to use AMICO with ActiveAx. However my qspace is 2D, all diffusion perpendicular to the fibers. Is it possible to : 
(1) fix the orientations theta/phi
OR
(2) specify my own modelfit function (that handles 2D qspace) written in MATLAB

Best regards 
Tom Mingasson

**Comment by Poumtchipa** [comment]
I changed 'AMICO_Fit.m' : 

- : [ ~, ~, V ] = AMICO_FitTensor( y, bMATRIX );
+ : V = [0, 0, 1];

Is it the thing to do ?

**Comment by daducci** [comment]
Hi Tom,

this way you not estimating anymore the fiber orientation and you are assuming it's along the z-axis. If this is always the case, then yes, this modification will do.

Also, as your acquisition is always perpendicular to the fibers, you can save time/space and avoid computing the LUT for all possible orientations by assuming your response function is isotropic (in 2D it is) by specifying "true" to the last parameter in the "AMICO_RotateKernel" call.

Does this help?

Best,
Ale

**Comment by TomMingasson** [comment]
Hi,

Thanks for your answer. 

Yes, it's always the case : fibers are always along z-axis. 

I tried to specify "true" in AMICO_ResampleKernel and in AMICO_RotateKernel (this within GenerateKernels). 

But I have the following error : screen print in photo attached. 

Do you have an idea for solving this ? 

Best regards,

Tom Mingasson



Date: Thu, 14 Jul 2016 03:18:02 -0700

**Comment by daducci** [comment]
Hi Tom,

I cannot see the image. Can you please post it again?

Thanks!
Ale

**Comment by TomMingasson** [comment]
Hi,

Here again the Screen Shot in attachement. Or a dropbox link in case it doesn't work : https://www.dropbox.com/s/iscun48z06p3xpl/Screen%20Shot%202016-07-14%20at%202.45.53%20PM.png?dl=0.  

Hope it's ok. 

Thanks,
Tom

Date: Fri, 15 Jul 2016 05:59:48 -0700

**Comment by daducci** [comment]
Hi,

I think there's something strange in your scheme file, as there seem to be 331 DWI volumes that are recognized as 299 different shells. Do you think you could share your data with me? I'm not gonna use your data other than debugging reasons and I will delete the data afterwards.

@davidrs06 : have you ever experience this issue?

PS: do you get the same error also with the python version? In any case, I suggest you try using the python code, if possible.

**Comment by davidrs06** [comment]
The ResampleKernels method of the ActiveAx model expects AMICO_ResampleKernel to return a matrix of size [KERNELS.nS nIC 181 181] for the restricted and hindered compartments. Changing the size of KERNELS.Aic and KERNELS.Aec at initialisation (lines 146 and 149) to [KERNELS.nS nIC] and [KERNELS.nS nEC] should solve this issue.

The problem will be the same in the python implementation as the 181x181 rotation matrix is hardcoded by default.

Let us know if you run into other issues.

Cheers,
David

**Comment by TomMingasson** [comment]
Hi,

Not sure you receive my last email. So I post it here on gitHub.

As you told me : 
- I changed the size of KERNELS.Aic and KERNELS.Aec at initialisation (lines 146 and 149).
- I set to true the variable isIsotropic everytime it appears, following your advice. For AMICO_RotateKernel and for AMICO_ResampleKernel for restricted/hindered/isotropic in AMICO_ACTIVEAX.m

I have 299 shells because I fix the gradient direction (gx=1, gy=0, gz=0) and I vary the gradient strength ||G|| between 0 and 80 mT/m.

I have no error :

`-> Precomputing rotation matrices for l_max=12:
   [ already computed ]

-> Loading and setup:
    * Loading DWI...
        - dim    = 64 x 64 x 3 x 331
        - pixdim = 0.156 x 0.156 x 0.002
    * Loading SCHEME...
        - 331 measurements divided in 299 shells (31 b=0)
    * Loading MASK...
        - dim    = 64 x 64 x 3
        - voxels = 2309
   [ DONE ]

-> Generating kernels with model "ActiveAx" for protocol "AMICO":
   [=========================]
   [ 40.4 seconds ]

-> Resampling rotated kernels for subject "Gmax80_opt":
   [=========================]
   [ 0.9 seconds ]

-> Fitting "ActiveAx" model to 2309 voxels:
   [=========================]
   [ 0h 0m 1s ]

-> Saving output to "AMICO/*":
    - CONFIG.mat [OK]
    - FIT_dir.nii [OK]
    - AMICO/FIT_v.nii [OK]
    - AMICO/FIT_a.nii [OK]
    - AMICO/FIT_d.nii [OK]
   [ DONE ]
`
But I obtain images (Fit_v.nii, Fit_d.nii...) with zero intensity everywhere...

Here is  the data and the scheme I use : https://www.dropbox.com/sh/t5uek97sl1834uq/AACiM46Zlw5JGMtfwqLc1Jama?dl=0 

Regards,

**Comment by daducci** [comment]
Hi Tom,

Usually, when the output maps are empty/nan, this is due to a wrong installation of the SPAMS libraries.
Can you check these discussions (#18, #24) and see whether this applies to you as well?

Ale

PS: I use the python implementation, but they should be equivalent

**Comment by TomMingasson** [comment]
It works ! I just had to change V correctly. 

PAST : [ ~, ~, V ] = AMICO_FitTensor( y, bMATRIX );
NEW : V = [0,0,1 ; 0,1,0 ; 1,0,0]    (and not V = [0, 0, 1] like I did before...). 

I continue to specify "true" in AMICO_ResampleKernel and in AMICO_RotateKernel (this within GenerateKernels).

Best,
Tom

**Comment by daducci** [comment]
Good, I'm glad it worked!

Best,
Ale

**Comment by tanguyduval** [comment]
Thanks for this great help Alessandro! 

Just note that fixing the direction makes AMICO much faster to generate kernels (~30 s on our computers), and reduces drastically the amount of memory used. For large scheme (>700 images) this is the only way to prevent memory saturation. 

On standard 3D qspace sampling of the spinal cord. we tried with and without fixing the direction V and it leads to the same results for both NODDI and ActiveAx (because fibers are basically in the Z direction).
I think it might help also people who want to use ActiveAx in the Corpus Callosum.

The only issue is when the slice aren't perfectly perpendicular to the Spinal cord or the CC fibers...

Best,
Thanks a lot,
Tanguy

**Comment by daducci** [comment]
Yes, this is expected: when you specify that your response functions are isotropic, there's no need to precompute and store all rotated versions of the response functions, so you save both time and space!
