### ISSUE TITLE
Problems generating the signal with datasynth

### ISSUE THREAD

**Issue by Hamzaumn** [daducci/AMICO#3]
Hi,
I am trying to run ActiveAx tutorial and getting following error:

Error using AMICO_ACTIVEAX/GenerateKernels (line 69)
[AMICO_ACTIVEAX.GenerateKernels] Problems generating the signal with datasynth

Error in AMICO_GenerateKernels (line 72) CONFIG.model.GenerateKernels( ATOMS_path, schemeHR, AUX, idx_IN, idx_OUT );

Otherwise, I am using CAMINO and generating synthetic data with 'datasynth' works fine. I am using Matlab on Linux Redhat. Probably it is related to calling CAMINO commands from MATLAB.
Regards

**Comment by daducci** [comment]
Hi!
Usually, it is a problem with the the configuration of the "CAMINO_path" configuration variable in AMICO_Setup.m. Did you set it top pint to the camino/bin/ folder?

**Comment by Hamzaumn** [comment]
Yes I did give the path. Above error is when I set the path to: 
/home/.../owner/camino
because I run all CAMINO commands in the CAMINO folder, but when I set the path to bin i.e.,
/home/.../owner/camino/bin
It throws following error:
java executable not found. Unable to run command

Error using AMICO_ACTIVEAX/GenerateKernels (line 69)
[AMICO_ACTIVEAX.GenerateKernels] Problems
generating the signal with datasynth
Error in AMICO_GenerateKernels (line 72)
        CONFIG.model.GenerateKernels( ATOMS_path, schemeHR, AUX, idx_IN, idx_OUT );

**Comment by daducci** [comment]
Ah ok. I guess it could be because you might not have the Java binaries in your global path (login shell), so you see them only when you open a normal shell (non-login shell). If this is the case, MATLAB does not "see" Java executables in his path and you get this error. You can solve this by setting Java in your .bash_profile. See [here](http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html) for help.
Does this solve your problem?

**Comment by Hamzaumn** [comment]
Thanks the above issue is resolved.

But while fitting I am getting following error:

Attempt to execute SCRIPT mexLasso as a function:
/home/.../owner/spams-matlab/src_release/mexLasso.m

Error in AMICO_ACTIVEAX/Fit (line 234)
        x = full( mexLasso( yy, AA,
        CONFIG.OPTIMIZATION.SPAMS_param ) );
Error in AMICO_Fit (line 42)
            vox_MAPs = CONFIG.model.Fit( y, i1,i2 );
The paths are entered correctly, do I need to give the path in .bash_profile as well?

**Comment by Hamzaumn** [comment]
The specific error is now:

-> Fitting "ActiveAx" model to 338 voxels:
Invalid MEX-file
'/home/.../owner/spams-matlab/build/mexLasso.mexa64':
dlopen: cannot load any more object with static TLS

Error in AMICO_ACTIVEAX/Fit (line 234)
        x = full( mexLasso( yy, AA,
        CONFIG.OPTIMIZATION.SPAMS_param ) );

Error in AMICO_Fit (line 42)
            vox_MAPs = CONFIG.model.Fit( y, i1, i2 );

Error in Active_Ax_tutorial (line 31)
AMICO_Fit()

**Comment by daducci** [comment]
It seems a problem with the SPAMS library (mexLasso solver). Is it installed/configured properly?
Btw, on which platform are you (OSX, Linux)?

**Comment by Hamzaumn** [comment]
I am working on Linux Redhat. 
I have installed SPAMS and launching Matlab from .sh generated after SPAMS installation. However, I'll reinstall and update.

**Comment by daducci** [comment]
I've never tested it on Redhat, but it should work. So far I've seen people using it only on Ubuntu and OSX.
Does SPAMS work properly on Redhat? Can you run their demos?

**Comment by Hamzaumn** [comment]
I found the following helpful, and it is working now.
http://www.mathworks.com/matlabcentral/answers/137228-setup-mex-compiler-for-r2014a-for-linux

**Comment by daducci** [comment]
Great! Please let me know if you encounter any other issue.
