### ISSUE TITLE
Error : Problems generating the signal with datasynth

### ISSUE THREAD

**Issue by SophieSebille** [daducci/AMICO#30]
Hello,

First, thank you for your excellent software!

I am trying to run ActiveAx on some ex-vivo monkey data and I got the following error with AMICO_GenerateKernels :
	* Creating high-resolution scheme:
	  [ DONE ]
	* Simulating kernels with "ActiveAx" model:
		- A_001... Error using AMICO_ACTIVEAX/GenerateKernels (line 68)
[AMICO_ACTIVEAX.GenerateKernels] Problems generating the signal with datasynth
Error in AMICO_GenerateKernels (line 72)
        CONFIG.model.GenerateKernels( ATOMS_path, schemeHR, AUX, idx_IN,
        idx_OUT );

I run the NODDI model on these data without a problem. I also run the ActiveAx tutorial without the above issue. Do you have any idea what the problem might be ?

Best,
Sophie

**Comment by daducci** [comment]
Hi Sophie,

it might be a problem with the scheme file you're using. In fact, as you can successfully run the tutorial, I'd say that it's not a problem with the Camino installation.
Could you share your scheme file?

Thanks,
Ale

**Comment by SophieSebille** [comment]
Thank you for your reply. I used the command fsl2scheme to get my scheme file. I also used that command in my code : CONFIG.b0_thr = 50. I put the .txt extension so I can enclosed it in this message.
Sophie
[camino.sheme.txt](https://github.com/daducci/AMICO/files/505719/camino.sheme.txt)

**Comment by daducci** [comment]
I don't see anything "clearly wrong" in your scheme file. Only thing: are the b-values up to 10k? So it seems from the data.

In case, would it be possible for you to share your dataset privately with me so that I can check and see what's causing your issues? Of course, after the test I would erase the data and never use it again.

**Comment by SophieSebille** [comment]
Yes, we have 4 shells : 
- 10 000 with 69 directions including 6 A0
- 4 0000 with 32 directions including 1 A0
- 1 000 with 16 directions including 1A0
- 500 with 8 directions including 1A0
I can share my dataset privately without an issue. I will send you an e-mail.

**Comment by daducci** [comment]
A `VERSION: BVECTOR` scheme file was being used to simulate signal according to the `cylinder` model, but indeed a `VERSION: STEJSKALTANNER` is needed (i.e. full sequence description).
