### ISSUE TITLE
Error : Problems generating the signal with datasynth

### ISSUE THREAD

**Issue by huchengMRI** [daducci/AMICO#32]
Hi, Alessandro,

Thank you for this tool! It's wonderful.
I ran into the error of "Problems generating the signal with datasynth" when I processed the tutorial data. The error was exactly the same as SophieSebille described in her post. The scheme file and the binary mask were downloaded from the website (https://github.com/daducci/AMICO/tree/master/matlab/doc/demos/ActiveAx). The path to java was added successfully. We are running matlab 2016a. I tried to run "datasynth -synthmodel compartment 1 CYLINDERGPD ..." in the command line, there was no error but also no output. 
Could you help us to resolve this issue?
FYI, I performed NODDI with the software without any problem before.
Thank you!

Hu

**Comment by daducci** [comment]
Hi Hu,

Sibille had an error because she was trying to fit ActiveAx but using a scheme file without the detailed information about the acquisition protocol (Delta, delta, G and TE for each sample); she was using a scheme file with only b-values, so Camino returned with an error as expected.
Nonetheless, this is quite strange as you indeed downloaded the scheme file from the demo.

Possible suggestions:

1. Check if by any chance the scheme file you downloaded is corrupted;

2. Can you check if you can manually run "datasynth" from within matlab and not from the shell? Peraphs you have correctly set the path for the bash shell but this path is "not seen" from the matlab environment.

Let me know,
Ale

**Comment by huchengMRI** [comment]
Hi Ale,

Thank you for your quick reply.
I don’t think the scheme file is corrupted. Attached please find the generated protocol_HR.scheme.
I ran the following command in matlab and the return value was 1.
system('/usr/local/camino/bin/datasynth -synthmodel compartment 1 CYLINDERGPD 6.000000E-10 0 0 1.000000E-08 -schemefile /home/hucheng/data/test/microstructure/kernels/ACTIVEAX/protocol_HR.scheme -voxels 1 -outputfile /tmp/tpcacaffc6_d9dc_4906_a37c_226772c33401.Bfloat 2> /dev/null')
Even there was no error when I ran '/usr/local/camino/bin/datasynth -synthmodel compartment 1 CYLINDERGPD 6.000000E-10 0 0 1.000000E-08 -schemefile /home/hucheng/data/test/microstructure/kernels/ACTIVEAX/protocol_HR.scheme -voxels 1 -outputfile /tmp/tpcacaffc6_d9dc_4906_a37c_226772c33401.Bfloat 2> /dev/null' in the shell, I don’t think it gave me any results, the output file was not created at all.
I’m running redhat 7. Any thoughts to trouble shoot?

Regards,

Hu

**Comment by daducci** [comment]
I suspect your matlab environment cannot directly access the Camino executables. Can you run the same command as before but avoiding to specify the full path to datasynth (i.e. `/usr/local/camino/bin/`)?

`system('datasynth -synthmodel compartment 1 CYLINDERGPD 6.000000E-10 0 0 1.000000E-08 -schemefile /home/hucheng/data/test/microstructure/kernels/ACTIVEAX/protocol_HR.scheme -voxels 1 -outputfile /tmp/tpcacaffc6_d9dc_4906_a37c_226772c33401.Bfloat 2> /dev/null')`

Does it run or you get the same error?

**Comment by surendra116083** [comment]
Hello @daducci Professor Daducci,
I run this code.
system('datasynth -synthmodel compartment 1 CYLINDERGPD 6.000000E-10 0 0 1.000000E-08 -schemefile /home/hucheng/data/test/microstructure/kernels/ACTIVEAX/protocol_HR.scheme -voxels 1 -outputfile /tmp/tpcacaffc6_d9dc_4906_a37c_226772c33401.Bfloat 2> /dev/null')

It outputs 1.

Would you please clarify for me that this is with an error or without error?

Best Regards,
Suren

**Comment by daducci** [comment]
Dear Suren,

what do you mean by "it outputs 1"? An error message or this is the content of the output file? If this is the case, usually it means that the values in the scheme file, or the parameter such as the diffusivity etc, have a wrong scale. Could you check?

**Comment by surendra116083** [comment]
Respected @daducci Professor Daducci,

Yes, the content of the output is 1.

I have attached a screenshot here. If this is an error, would you please guide me on how can I correct this issue?

![image](https://user-images.githubusercontent.com/24285775/121217679-0a2c9480-c8bd-11eb-84b7-99c002f08f3f.png)

**Comment by surendra116083** [comment]
Respected @daducci Professor Daducci,

Thank you very much. The code is working well.

Best Regards,
Suren

**Comment by surendra116083** [comment]
Hello @MarioOcampo Mario,

I have one issue with datasynth as well. When I run datasynth in the terminal, I get this:

![image](https://user-images.githubusercontent.com/24285775/121505458-d1f09780-ca1d-11eb-8b6e-d5d589fa03c7.png)

Would you guide me through this issue? Again, I get results without any other errors.

Best,
Suren

**Comment by MarioOcampo** [comment]
Hello @surendra116083 ,
you are missing parameters, check your previous [comment](https://github.com/daducci/AMICO/issues/32#issuecomment-856891421) and the documentation of [datasynth]( http://camino.cs.ucl.ac.uk/index.php?n=Man.Datasynth).
Let us know if you solve the problem,
 
Best
Mario

**Comment by surendra116083** [comment]
Hello @MarioOcampo Mario,

Thank you very much. I exported the path of java and javac of Camino in /.bashrc of vmware. But if still "datasynth" throws "java executable not found. unable to run the command". I am wondering what may be the issue.

Best
Suren

**Comment by MarioOcampo** [comment]
That is a different issue than the one you reported.
Can you share the complete error?
