### ISSUE TITLE
error with ae.fit

### ISSUE THREAD

**Issue by bacaron** [daducci/AMICO#40]
Hello,

I'm having issues running ae.fit().  Here's the output:

"-> Fitting "NODDI" model to 207694 voxels:
   [                                                  ]   0.0%---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-21-1f0f7d5e3f54> in <module>()
----> 1 NODDI_fxn("1_002")

/N/dc2/projects/lifebid/Concussion/concussion_test/bin/NODDI_fxn.py in NODDI_fxn(subject)
      9         ae.generate_kernels( regenerate = True )
     10         ae.load_kernels()
---> 11         ae.fit()
     12         ae.save_results()
     13         print("NODDI model generation complete")

/N/dc2/projects/lifebid/code/bacaron/AMICO/amico/core.pyc in fit(self)
    325 
    326                     # dispatch to the right handler for each model
--> 327                     MAPs[ix,iy,iz,:], DIRs[ix,iy,iz,:], x, A = self.model.fit( y, dirs.reshape(-1,3), self.KERNELS, self.get_config('solver_params') )
    328 
    329                     # compute fitting error

/N/dc2/projects/lifebid/code/bacaron/AMICO/amico/models.pyc in fit(self, y, dirs, KERNELS, params)
    579         i1, i2 = amico.lut.dir_TO_lut_idx( dirs[0] )
    580         A = np.ones( (len(y), nATOMS), dtype=np.float64, order='F' )
--> 581         A[:,:nWM] = KERNELS['wm'][:,i1,i2,:].T
    582         A[:,-1]  = KERNELS['iso']
    583 

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices"

Not exactly sure what the issue is.  Any help would be greatly appreciated!

Thank you,
Brad Caron

**Comment by anbai106** [comment]
I use the data that you offered in the demo, from matlab toolbox of noddi, and I got the same errors, did you find the solution???

**Comment by bacaron** [comment]
Hao,

Thank you for looking into this and providing a solution!  I'll try that tonight and see if it works.

Thank you,
Brad

**Comment by davidrs06** [comment]
Hao's fix was merged to the code of AMICO, you can update your code by pulling the latest version and reinstalling it on your computer.

Thanks for spotting and reporting this issue quickly.

Best regards,
David
