### ISSUE TITLE
help on ae.fit()

### ISSUE THREAD

**Issue by graffard** [daducci/AMICO#43]
Hello,
With ubuntu 16.04, I wanted to install Amico.
After a complete installation
I get this error in use
"
  Ae.fit ()
   File "/usr/local/lib/python2.7/dist-packages/amico/core.py", line 300, in fit
     MAPs [ix, iy, iz ,:], DIRs [ix, iy, iz ,:], x, A = self.model.fit (y, dirs.reshape (-1,3), self.KERNELS, self. Get_config ('solver_params'))
   File "/usr/local/lib/python2.7/dist-packages/amico/models.py", line 553, in fit
     A [:,: - 1] = KERNELS ['wm'] [:, i1, i2,:] T
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
"
can you help me ?
thank you

Gérard

**Comment by davidrs06** [comment]
Hello Gérard !

This issue was recently posted and solved by [Hao](https://github.com/daducci/AMICO/commit/c1449d5e47f04fa02711bd6204591ec730946a91). It is apparently due to an update of numpy. If you re-install a fresh version of AMICO it should solve the problem. Either download the zip file from the [AMICO repository](https://github.com/daducci/AMICO), or `cd` to a folder where you want the code to be saved and run the following:
```
git clone https://github.com/daducci/AMICO
cd AMICO
pip install -U .
```
This will download the most recent version of AMICO and install a fresh copy on your computer.
Let me know if this works.

Best regards,
David

**Comment by graffard** [comment]
Thank you for your quick rest.
After a new installation of Amico here is the error
     Ae.fit ()
   File "/usr/local/lib/python2.7/dist-packages/amico/core.py", line 327, in fit
     MAPs [ix, iy, iz ,:], DIRs [ix, iy, iz ,:], x, A = self.model.fit (y, dirs.reshape (-1,3), self.KERNELS, self. Get_config ('solver_params'))
   File "/usr/local/lib/python2.7/dist-packages/amico/models.py", line 599, in fit
     X = spams.lasso (np.asfortranarray (yy), D = np.asfortranarray (An), ** params) .todense () A1
   File "/usr/lib/python2.7/site-packages/spams.py", line 439, in lasso
     (X, D, return_reg_path, L, lambda1, lambda2, mode, pos, ols, numThreads, max_length_path, verbose, cholesky)
   File "/usr/lib/python2.7/site-packages/spams_wrap.py", line 201, in lassoD
     Return _spams_wrap.lassoD (* args)
RuntimeError: matrix arg 1 must be a 2d double Fortran Array

thank you
Best regards,
Gérard

**Comment by davidrs06** [comment]
Ok, thanks for reporting this. Which version of spams are you using ?

**Comment by graffard** [comment]
the spams version is v2.6-2017-03-28

**Comment by daducci** [comment]
This SPAMS version just came out, probably they have changed something that needs to be accounted for in AMICO. Could you, for the time being, try to install and setup AMICO with an older version of SPAMS?

**Comment by davidrs06** [comment]
@daducci : Could it be because the data is loaded as [float32](https://github.com/daducci/AMICO/blob/master/amico/core.py#L94) ?
@graffard : Can you try the following: replace line 599 by `x = spams.lasso( np.asfortranarray(yy.astype(np.double)), D=np.asfortranarray(An), **params ).todense().A1` in your code and run `pip install -U .` again. Does it change something ?

**Comment by graffard** [comment]
@davidrs06 : after change in line 599 and pip install -U . no change it's the same error.

**Comment by graffard** [comment]
@daducci : with spams 2.5 and modification line 599 
    ae.fit()
  File "/usr/local/lib/python2.7/dist-packages/amico/core.py", line 327, in fit
    MAPs[ix,iy,iz,:], DIRs[ix,iy,iz,:], x, A = self.model.fit( y, dirs.reshape(-1,3), self.KERNELS, self.get_config('solver_params') )
  File "/usr/local/lib/python2.7/dist-packages/amico/models.py", line 600, in fit
    x = spams.lasso( np.asfortranarray(yy.astype(np.double)), D=np.asfortranarray(An), **params ).todense().A1
  File "/usr/lib/python2.7/site-packages/spams.py", line 439, in lasso
    (indptr,indices,data,shape) = spams_wrap.lassoD(X,D,return_reg_path,L,lambda1,lambda2,mode,pos,ols,numThreads,max_length_path,verbose,cholesky)
  File "/usr/lib/python2.7/site-packages/spams_wrap.py", line 201, in lassoD
    return _spams_wrap.lassoD(*args)
RuntimeError: matrix arg 1 must be a 2d double Fortran Array

**Comment by daducci** [comment]
And without that modification at line 599? I mean, installing latest version of AMICO and SPAMS 2.5? It works out of the box on our systems (both linux and OSX).

**Comment by graffard** [comment]
installing  latest version of AMICO and SPAMS 2.5  
result :"

-> Loading data:
	* DWI signal...
		- dim    = 164 x 128 x 48 x 30
		- pixdim = 1.000 x 1.000 x 1.000
	* Acquisition scheme...
		- 30 samples, 2 shells
		- 3 @ b=0 , 6 @ b=800.0 , 21 @ b=2000.0
	* Binary mask...
		- dim    = 164 x 128 x 48
		- pixdim = 1.000 x 1.000 x 1.000
		- voxels = 80767

-> Preprocessing:
	* Normalizing to b0... [ min=0.02,  mean=0.75, max=8.86 ]
	* Keeping all b0 volume(s)...
   [ 1.3 seconds ]

-> Creating LUT for "NODDI" model:
   [ LUT already computed. Call "generate_kernels( regenerate=True )" to force regeneration. ]

-> Resampling LUT for subject "430":
   [ 69.5 seconds ]                                            

-> Fitting "NODDI" model to 80767 voxels:
   [                                                  ]   0.0%
Traceback (most recent call last):
  File "***************.py", line 35, in <module>
    ae.fit()
  File "/usr/local/lib/python2.7/dist-packages/amico/core.py", line 327, in fit
    MAPs[ix,iy,iz,:], DIRs[ix,iy,iz,:], x, A = self.model.fit( y, dirs.reshape(-1,3), self.KERNELS, self.get_config('solver_params') )
  File "/usr/local/lib/python2.7/dist-packages/amico/models.py", line 599, in fit
    x = spams.lasso( np.asfortranarray(yy), D=np.asfortranarray(An), **params ).todense().A1
  File "/usr/lib/python2.7/site-packages/spams.py", line 439, in lasso
    (indptr,indices,data,shape) = spams_wrap.lassoD(X,D,return_reg_path,L,lambda1,lambda2,mode,pos,ols,numThreads,max_length_path,verbose,cholesky)
  File "/usr/lib/python2.7/site-packages/spams_wrap.py", line 201, in lassoD
    return _spams_wrap.lassoD(*args)
RuntimeError: matrix arg 1 must be a 2d double Fortran Array
""

i run many amico studies  on system ubuntu 14.04 without problems.

**Comment by graffard** [comment]
I have tested SPAMS 2.5.
I have an error on the lasso test.
Thank you very much for your attention.
I will return when I have a good installation of SPAMS 2.5.
thank you very much
Best regards,
Gérard

**Comment by graffard** [comment]
After installing NumPy 1.12.1
  I no longer calculate the noddis.
Back to NumPy 1.11.0 all goes well
Thank you very much for your help
Best regards,
Gérard
