### ISSUE TITLE
Small variation in b-values interpreted as unique shells

### ISSUE THREAD

**Issue by MariaICL** [daducci/AMICO#48]
Pretty much the same issue as the one referred to here (https://github.com/daducci/AMICO/issues/10), but in the python version of AMICO.
I have recently started using the python version (currently trying to write a nipype wrapper for it, to incorporate AMICO into a NODDI analysis pipeline), and I came across the problem of minimal variations in the b values being considered as different shells.
I don't have much experience in python (much less than in Matlab), so I don't really know how to fix the issue in a similar manner (make fsl2scheme round the values). Any tips?
Thanks!

**Comment by daducci** [comment]
Hi @MariaICL ,
sorry for being so late. Did you try to use the analogous function we write in python?
[https://github.com/daducci/AMICO/blob/master/amico/util.py#L4](url)

Let me know if this helps!
