### ISSUE TITLE
fsl2scheme delimiter bug

### ISSUE THREAD

**Issue by anbai106** [daducci/AMICO#49]
Hi, 
I am using fsl2scheme to create the scheme file, but I found that when use np.loadtxt, it is better not to define the delimiter like you did in the code(delimiter is optional with kwargs):

>   if kwargs:
         delimiter = kwargs.get('delimiter') 
    # load files and check size
    bvecs = np.loadtxt( bvecsFilename, delimiter=delimiter)
    bvals = np.loadtxt( bvalsFilename, delimiter=delimiter)

if we do not define delimiter in the kwargs, this will give us error, cuz in the source code, delimiter is not optional, it is a must, so just not to use this parameters:

>     # if kwargs:
    #     delimiter = kwargs.get('delimiter') ### changed by Hao, actually, this should not be used 
    for reading bvecs and bvals

    # load files and check size
    bvecs = np.loadtxt( bvecsFilename)
    bvals = np.loadtxt( bvalsFilename)

I do not know why you added this, cuz I think before you did not have this unless you did in on purpose.

Thanks in advance

Hao

**Comment by daducci** [comment]
Hi @anbai106 ,

we added this extra parameter to allow more flexibility in the format that the `bvals` and `bvecs` may have. Indeed there is a bug if you do not specify the `delimiter` parameter. Please check the fix I'll propose in a second.

**Comment by GusZimmerman** [comment]
Hi,

Is there a fix for this?

Thanks.
