### ISSUE TITLE
Ex-vivo imaging

### ISSUE THREAD

**Issue by davidaustralia** [daducci/AMICO#5]
Dear Daducci et al.,

Firstly, thank you for your excellent contribution.

Is it possible to implement the NODDI model 'WatsonSHStickTortIsoVIsoDot_B0' which includes an isotropically restricted compartment for ex-vivo imaging? 

Regards,

David

**Comment by daducci** [comment]
Dear David,
glad you find our software useful!

Yes, of course, it is totally feasible and actually easy (@davidrs06): it just requires to add a column to the dictionary.
We are a bit busy on some other projects before ISMRM, but we see what we can do, ok?

Best,
Alessandro

**Comment by davidaustralia** [comment]
Dear Alessandro,

Thank you very much for your prompt reply. I understand that you are busy getting ready for ISMRM and so I'm looking forward, patiently(!), to this valuable update!  

Thanks again and best regards,

David

**Comment by daducci** [comment]
Are you going to ISMRM? If so, we might speak there in person.

Also, do you think you could share with us one ex-vivo dataset for us to test (of course, privately)? Actually, we don't own any such dataset, so it would be great to have one for the testing.

Alessandro

**Comment by davidaustralia** [comment]
Unfortunately no, I won't be going to ISMRM this year but I will have colleagues attending.

I'd be happy to provide an ex-vivo dataset for your testing. I will contact you directly through the email address on your NeuroImage paper to discuss further.

Regards,

David

**Comment by daducci** [comment]
I tried to add a new parameter, isExvivo, to add the 'dot' compartment in case of ex-vivo data. Can you try to test it with your data? Perhaps you'd need to play with the regularization as well.

**Comment by dicemt** [comment]
I'm not David, but by using isExvivo and adjusting regularization parameters, I could get AMICO-NODDI images that are 'qualitatively similar' to the original NODDI model.
(I mean "the NODDI ('WatsonSHStickTortIsoVIsoDot_B0') and AMICO images are so similar that I cannot distinguish between them at first sight, but I do not compare them quantitatively").

Thank you so much.

Daisuke

**Comment by daducci** [comment]
Thanks a lot Daisuke!

Yes, please keep me posted.

**Comment by jd1986** [comment]
Hi Daisuke, I am also looking at using AMICO for ex-vivo data. What sort of values did you change the regularization parameters to?
Thanks

**Comment by tanguyduval** [comment]
Hello there,

I was really impressed by the gain in robustness in AMICO fitting, great job!
I would like to try that on ex vivo dataset, would it be possible to implement isExvivo for CAMINO also?

Thanks a lot,
Best,
Tanguy

**Comment by davidrs06** [comment]
Concerning [Daisuke's comment](https://github.com/daducci/AMICO/issues/5#issuecomment-150078610), I think the `isExVivo` flag was not really set to True in the experiment, as it should have raised an error (see Issue #35). Could you try to run again your experiment, this time using:
```python
ae = amico.Evaluation("Study", "Subject")
ae.load_data(dwi_filename = "DWI.nii", scheme_filename = "scheme.txt", mask_filename = "mask.nii", b0_thr = 0)
ae.set_model("NODDI")
ae.generate_kernels()
ae.load_kernels()
ae.model.isExvivo = True
ae.fit()
ae.save_results()
```

**Comment by goals2008** [comment]
Hi  @daducci and @davidrs06 
  
   We have the latest code checked out and are trying to use AMICO on exvivo dataset by setting below flag
      >> ae.model.isExvivo = True

However we are running into following issue

  _core.py", line 254, in load_kernels_
    
_self.KERNELS = self.model.resample( self.get_config('ATOMS_path'), idx_OUT, Ylm_OUT, self.get_config('doMergeB0') )
TypeError: resample() takes exactly 4 arguments (5 given)_

Can you please assist if any additional settings need to be made for exVivo. Also can you please share some information on the regularization parameters that can be applied.

Thanks,
Prasanna

**Comment by davidrs06** [comment]
Good afternoon Prasanna,
This error is strange, it seems that resample() is given 5 arguments, although only 4 are given (ATOMS_path, idx_OUT, Ylm_OUT and doMergeB0).

Have you tried the [NODDI tutorial](https://github.com/daducci/AMICO/blob/master/doc/demos/NODDI_01.md) ? You can activate the exvivo flag just after selecting the NODDI model:
```
import amico
amico.core.setup()
ae = amico.Evaluation("Study01", "Subject01")
amico.util.fsl2scheme("Study01/Subject01/NODDI_protocol.bval", "Study01/Subject01/NODDI_protocol.bvec")
ae.load_data(dwi_filename = "NODDI_DWI.img", scheme_filename = "NODDI_protocol.scheme", mask_filename = "roi_mask.img", b0_thr = 0)
ae.set_model("NODDI")
ae.model.isExVivo = True
ae.generate_kernels()
ae.load_kernels()
ae.fit()
ae.save_results()
```
Could you give it a try and let me know if you still get the same error ?
Best regards,
David

**Comment by davidrs06** [comment]
Also, are you sure you re-installed properly AMICO after checking out the last version ? This error might appear if the `models.py` module was not updated. To be sure to have a clean installation, try running `pip install -U .` from the AMICO folder.
Cheers,
David

**Comment by goals2008** [comment]
Hi David,

  Yes I am using the same syntax as mentioned above, setting isExvivo flag
after setting NODDI model. I think 5 arguments are passed internally  in
the new code when model fit is called.

Thanks,
Prasanna

**Comment by davidrs06** [comment]
Using the NODDI tutorial, I'm only able to replicate the error message if I use the current version of `core.py` and the old version of `models.py`, which makes me think there was a problem when you updated AMICO.

Could you try opening python and run
```
import amico
help(amico.models.NODDI.resample)
```
and post the message that is displayed ? If `models.py` is up-to-date, you should have the following message

> Help on method resample in module amico.models:
> 
> resample(self, in_path, idx_out, Ylm_out, doMergeB0) unbound amico.models.NODDI method

Let me know what you get.
Cheers,
David

**Comment by goals2008** [comment]
Hi David,

   I do get below message when calling resample on updated module.

Help on method resample in module amico_fix.models:

resample(self, in_path, idx_out, Ylm_out, doMergeB0) unbound
amico_fix.models.NODDI method
(END)

Can you please let me know if there is any other configuration that I could
be missing. I will also try to recheck to install using pip install -U .

Thanks,
Prasanna

**Comment by davidrs06** [comment]
This is strange, I don't get any error if I follow the NODDI tutorial and use the script I posted before.

Could you try to clone the AMICO repository and install it from there ? `cd` to your Desktop folder, and run 
```
git clone https://github.com/daducci/AMICO
cd AMICO
pip install -U .
```
This should install a fresh copy on your computer. Can you then download the data for the NODDI tutorial and run the same script I posted above ? Including the exVivo flag.

Do you still get the same error ?

**Comment by goals2008** [comment]
Hi David,  Looks like it worked! Installing fresh copy helped. Thank you!

**Comment by davidrs06** [comment]
Great ! Let us know if you run into any strange behavior.
Have a nice weekend !
David

**Comment by goals2008** [comment]
Hi David,

   Setting isExvivo flag on NODDI dataset seem to have worked fine. However when running it on our dataset, looks like optimization is not working, we see 0.09, 0.19, 0.29.. values in OD. 

Here is more information on our exvivo dataset

	* DWI signal...
		- dim    = 128 x 192 x 128 x 410
		- pixdim = 0.300 x 0.300 x 0.300
	* Acquisition scheme...
		- 410 samples, 4 shells
		- 12 @ b=0 , 107 @ b=3000.0 , 103 @ b=6000.0 , 98 @ b=9000.0 , 90 @ b=12000.0

Can you please suggest if there are any configuration settings that may need to be changed?

Thanks,
Prasanna

**Comment by davidrs06** [comment]
You need to adapt the parallel diffusivity, as it is set by default to 1.7 mm<sup>2</sup>.s<sup>-1</sup>. A reasonable value would be 0.6x10<sup>-3</sup> mm<sup>2</sup>.s<sup>-1</sup> (see the work on ex-vivo synthetic simulations of [Alexander 2010](http://www.sciencedirect.com/science/article/pii/S1053811910007755)). You need to set the diffusivity before generating the kernels, as follows:
```
import amico
amico.core.setup()
ae = amico.Evaluation("Study01", "Subject01")
amico.util.fsl2scheme("Study01/Subject01/NODDI_protocol.bval", "Study01/Subject01/NODDI_protocol.bvec")
ae.load_data(dwi_filename = "NODDI_DWI.img", scheme_filename = "NODDI_protocol.scheme", mask_filename = "roi_mask.img", b0_thr = 0)
ae.set_model("NODDI")
ae.model.isExVivo = True
ae.model.dPar = 0.6E-3 # <== Sets the diffusivity of the model
ae.generate_kernels(regenerate = True) # <== Make sure to regenerate the kernels
ae.load_kernels()
ae.fit()
ae.save_results()
```
This should improve the fitting. Let us know how it goes.
Cheers,
David

**Comment by goals2008** [comment]
Ok setting the parallel diffusivity value along with isExvivo flag helped. We do have reasonable results now. Thank you!
