### ISSUE TITLE
Temporary Solution to SPAMS Multi-Threading Issue Affecting AMICO Computing Time.

### ISSUE THREAD

**Issue by gauvinalexandre** [daducci/AMICO#56]
As discussed in both issues #17 and #55, SPAMS multi-threading issue will use more cores while increasing the total time of processing. For example, my experience on a 1.75 mm isotropic human brain gave the following numbers to compute NODDI with AMICO:
- 1 thread: 6m 33s;
- 2 threads: 6m 47s;
- 3 threads: 07m 09s;
- default (all of my i7 8 threads): about 15m.

Here's how I managed to control the number of cores by adding a couple of code lines to my script:
```python
import os
import amico
...
nb_threads = 1
os.environ["OMP_NUM_THREADS"] = str(nb_threads)  # Has impact on a supercomputer
os.environ["MKL_NUM_THREADS"] = str(nb_threads)  # Has impact both on supercomputer and personal computer if you are using MKL

amico_eval = amico.Evaluation(data_dir, subject, output_path)
...  # Set models and parameters
solver_params = amico_eval.get_config('solver_params')
solver_params['numThreads'] = nb_threads
amico_eval.set_config('solver_params', solver_params)

amico_eval.generate_kernels()
amico_eval.load_kernels()
amico_eval.fit()
```
I think this is going to be necessary until SPAMS solve their issue, and then maybe we'll have even better computing times!

Thanks to @daducci and Félix Morency who helped me with this issue!

**Comment by MariaICL** [comment]
Does this fix still work? I have this error:


TypeErrorTraceback (most recent call last)
<ipython-input-8-68b23bb3b74d> in <module>()
      1 # Set models and parameters, https://github.com/daducci/AMICO/issues/56
      2 solver_params = ae.get_config('solver_params')
----> 3 solver_params['numThreads'] = nb_threads
      4 ae.set_config('solver_params', solver_params)

TypeError: 'NoneType' object does not support item assignment

**Comment by gauvinalexandre** [comment]
I'm sorry, I don't know, I am not working in the field anymore. @daducci ?

**Comment by davidrs06** [comment]
As discussed in #67, the `OMP_NUM_THREADS` and `MKL_NUM_THREADS` environmental variables might have to be set before importing `amico` in order to have an effect on spams.

**Comment by soichih** [comment]
I've set OMP_NUM_THREADS and MLK_NUM_THREADS to 1 via bash export prior to python excution, but AMICO is still running at/near 2000% cpu. 

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                             
21108 user      20   0 7976888   7.0g  16112 R  2046 11.9   1754:58 python  
```

It does seem to run much faster, but we'd like to limit the number of CPU usage to less than 8 core - as we are executing it HPC environment.  

We are using AMICO from last year in our docker container. Should I update it?

**Comment by MarioOcampo** [comment]
Hello @soichih,

did you set the variable `amico_eval.CONFIG['solver_params']['numThreads'] = 1`?

I'm using AMICO on Ubuntu 16. To control the number of threads I set the OMP_NUM_THREADS and MLK_NUM_THREADS to 1 via bash, like you did it, and set the variable `numThreads` in AMICO  (it is a parameter for SPAMS)  to 1 before executing the `fit()` command, like @gauvinalexandre  and @davidrs06 (in #67) indicated.

**Comment by soichih** [comment]
@MarioOcampo Thanks for the tip!

I've tried setting the config parameter, but for some reason it's not letting me.

```
import amico
import os

amico.core.setup()
ae = amico.Evaluation(os.getcwd(),"NODDI")
solver_params = ae.get_config('solver_params')
solver_params['numThreads'] = 1
```

```
  File "/mnt/scratch/hayashis/syncthing/git/app-noddi-amico/NODDI.py", line 20, in <module>
    solver_params['numThreads'] = 1
TypeError: 'NoneType' object does not support item assignment
```

Here is how I am installing amico

```
#install dipy and spams (and deps)
RUN conda install -y -c conda-forge dipy python-spams

#install amico (via pip)
RUN git clone https://github.com/daducci/AMICO.git && cd AMICO && pip install .

```

**Comment by MarioOcampo** [comment]
Hello @soichih,
after `ae = amico.Evaluation(os.getcwd(),"NODDI")` you have to call  `ae.set_model("NODDI")`, in this function the variable `solver_params` is created. Then you can set the parameter `numThreads`.

**Comment by soichih** [comment]
Ah ok thanks..

I was able to set the parameter, but the model fitting is still running way above the single core.

![image](https://user-images.githubusercontent.com/923896/68506191-0cd58c80-0237-11ea-997f-d623e32a5294.png)

I think it's just using all available cores?

**Comment by MarioOcampo** [comment]
What you report seems similar to what is described in #67 . Can you try what was suggested?

**Comment by soichih** [comment]
@MarioOcampo I tried the suggestion from #67 but it didn't work.

**Comment by soichih** [comment]
@MarioOcampo Never mind.. I just tested the suggested fix and it seems to work now. I guess I didn't test it right last year.

**Comment by MarioOcampo** [comment]
Excellent @soichih!,  
Did you do the same test that you posted in #67 or did you change any package or configuration?

**Comment by soichih** [comment]
Not really.. I did update our docker container (with amico 1.1?) last year, so it could be that I was stuck on the older version when I tested it. Here is the script that we ended up with
> https://github.com/brain-life/app-noddi-amico/blob/1.1/NODDI.py
