### ISSUE TITLE
MacOSX error with numpy.newaxis

### ISSUE THREAD

**Issue by mdesco** [daducci/AMICO#63]
Hey guys,

I'm getting this error only on my MacOSX version of AMICO. Same code, same data runs fine on Linux.

Traceback (most recent call last):
  File "NODDI_kaitlyn.py", line 48, in <module>
    ae.fit()
  File "/Users/desm2239/Research/Source/AMICO/python/amico/core.py", line 304, in fit
    MAPs[ix,iy,iz,:], DIRs[ix,iy,iz,:], x, A = self.model.fit( y, dirs.reshape(-1,3), self.KERNELS, self.get_config('solver_params') )
  File "/Users/desm2239/Research/Source/AMICO/python/amico/models.py", line 555, in fit
    A[:,:-1] = KERNELS['wm'][:,i1,i2,:].T
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Sounds familiar. I have this with numpy 1.13.1 and 1.14

Thanks

**Comment by daducci** [comment]
Thanks @mdesco for posting this, indeed it rings a bell... @David, isn't this error something you have already encountered?

**Comment by davidrs06** [comment]
Hi @mdesco ! Do you have the last version of AMICO installed ? It seems to me that line 555 of models.py doesn't correspond to the error message.

The command `A[:,:-1] = KERNELS['wm'][:,i1,i2,:].T` is at line [587](https://github.com/daducci/AMICO/blob/master/amico/models.py#L587) in the current version.

**Comment by davidrs06** [comment]
Any news regarding this issue ? Have you tried updating to the last version ?

Best regards,
David

**Comment by mdesco** [comment]
No. Was waiting for a suggestion.
I still have the problem and right now not using my mac for AMICO stuff…

Max

On Jun 27, 2018, at 05:30, David Romascano <notifications@github.com<mailto:notifications@github.com>> wrote:


Any news regarding this issue ? Have you tried updating to the last version ?

Best regards,
David

**Comment by davidrs06** [comment]
The suggestion was to update and install the last version of AMICO, as you might not have the latest version. Running the demo using the last version seems to work on my mac, using numpy-1.14.0. I think at some point the value of `i1` and `i2` were `float` values, which are not supported by numpy-1.14. Values were changed to `int` in commit https://github.com/daducci/AMICO/commit/d24f0989d9ab1f0f1b12f25f29497464f12bc681 in march last year.

Hope this helps, let me know if you still have the issue after testing this, when you have time.

Best regards,
David
