### ISSUE TITLE
Improper NODDI and ActiveAx fitting

### ISSUE THREAD

**Issue by yinkaola** [daducci/AMICO#65]
When I run NODDI and ActiveAx on one computer, I get images that are completely wrong. For example, with the original NODDI file, ODI produces 0.3 for most voxels except the CSF. I traced the problem to the generate_kernels(). When I run the program with kernels generated from python 2.7.15 and anaconda2-5.1.0 on a different computer, I get good results.

I use anaconda2-5.1.0. I have reinstalled python-spams, amico, camino but nothing has worked. I don't think the problem is from the python version because it used to work, but I am wondering if there is a setting in one of these programs that affects the output of ae.generate_kernels()

Thank you for any help you can offer

**Comment by daducci** [comment]
Hi @yinkaola ,
did you try deleting all the files in the `kernels` folder? Or, equivalently, by setting the parameter `regenerate = True`. Did you compare the files in that folder (`*.npy`) between the two machines?

**Comment by yinkaola** [comment]
yes I have tried both methods. If I move the kernels form the bad outcome to the good one, I get bad images. If I move from the good to the bad, I get good images. I have also attached images of one of the kernels generated for NODDI data when doing ActiveAx and NODDI fitting from both programs.
<img width="525" alt="good_activeax-a_001" src="https://user-images.githubusercontent.com/13862814/41980668-437a0842-79e4-11e8-84b6-08ed97c24615.png">
<img width="493" alt="good_noddi-a_001" src="https://user-images.githubusercontent.com/13862814/41980670-43982c3c-79e4-11e8-95b6-47f2ca545260.png">
<img width="474" alt="bad_activeax-a_001" src="https://user-images.githubusercontent.com/13862814/41980674-4a972524-79e4-11e8-9c5c-f469212b9808.png">
<img width="499" alt="bad_noddi-a_001" src="https://user-images.githubusercontent.com/13862814/41980675-4acb248c-79e4-11e8-8d3a-f8854605bbcf.png">

**Comment by davidrs06** [comment]
Hi @yinkaola ,
Starting with ActiveAx, could you check the values of the parameters for the dictionary, namely `ae.model.dPar`, `ae.model.Rs`, `ae.model.ICVFs` and `ae.model.d_ISOs` ? What are the values ? And are the values the same on both computers ?

**Comment by yinkaola** [comment]
**ActiveAx - good and bad**
ae.dPar -             N/A
ae.model.Rs -     array([1.00000000e-08, 5.00000000e-07, 8.94736842e-07, 1.28947368e-06,
                            1.68421053e-06, 2.07894737e-06, 2.47368421e-06, 2.86842105e-06,
                            3.26315789e-06, 3.65789474e-06, 4.05263158e-06, 4.44736842e-06,
                            4.84210526e-06, 5.23684211e-06, 5.63157895e-06, 6.02631579e-06,
                            6.42105263e-06, 6.81578947e-06, 7.21052632e-06, 7.60526316e-06,
                            8.00000000e-06])
ae.model.ICVFs - array([0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
ae.model.d_ISOs - array([0.002])

**NODDI - good and bad**
ae.dPar -             0.017
ae.model.Rs -     N/A
ae.model.ICVFs - N/A
ae.model.d_ISOs - N/A


The values are the same on both computers.

**Comment by davidrs06** [comment]
Ok, thank you for the information. Are you using the ActiveAx scheme, `ActiveAxG140_PM.scheme1` ?

**Comment by yinkaola** [comment]
No, this was done using the NODDI data

**Comment by davidrs06** [comment]
I installed anaconda2-5.1.0 for OSX, along with the last version of AMICO, using dipy-0.14.0, nibabel-2.3.0, numpy-1.14.5 and scipy-1.1.0. When running the NODDI demo, I get values that are different from both your kernels/NODDI/A_001.npy files...
Are you using the `NODDI_protocol.scheme` file generated using the `amico.util.fsl2scheme` tool ? To double check that the files are generated from the same data, could you check of the md5sum of the file `NODDI_protocol.scheme` is d950913da988d7aaa90f86ed48cf2b22 ? If that's the case, then do you see a difference in versions of numpy or scipy ?

**Comment by yinkaola** [comment]
I don't know what caused the issue initially, but instead of just the kernels folder, I deleted the "AMICO_aux_matrices_lmax=12.pickle" file and regenerated it with the amico.core.setup() command and I was able to get the proper outcomes again. Thank you for your help

**Comment by yinkaola** [comment]
I did use the NODDI_protocol.scheme file from the amico.util.fsl2scheme tool for the NODDI analysis and it has the same md5sum: d950913da988d7aaa90f86ed48cf2b22. The versions of the packages were also the same.

**Comment by davidrs06** [comment]
Glad you worked out what was happening. Just to check that we get the same kernels now, is the md5sum of the file kernels/NODDI/A_001.npy equal to ea16b56df895067f1f22788afec82da5 ?

**Comment by yinkaola** [comment]
Anaconda2-5.1.0

computer 1
A_001: 1bffa50f07941ed649cf7f6b0160e3b9
amico.core.setup() file: 16b1109ef6353de9e048dc5201ad78fa

computer 2
A_001: fefef4a69c8ebd40eecf2fbc0e1ec0c9
amico.core.setup() file: 55a58528a29b4097a503e370fafe37d8

Both my computers have different numbers from yours and themselves, and their amico.core.setup() files are different also.

I calculated the difference images of ODI in the 26th slice between both computers, and the mean of all pixels was 1.959E-8.

**Comment by davidrs06** [comment]
The difference between fits is indeed very small, even though it's strange to have different auxiliary matrices, as you have the same versions of dipy and numpy between computers and mine. Could it be the version of cPickle ? I have version 1.71, how about you ?

**Comment by yinkaola** [comment]
I found pickleshare(0.7.4) and cloudpickle(0.5.2). Is one of these the right package? I will also look for updates.

**Comment by davidrs06** [comment]
It should already be installed. In ipython, if you type import `import cPickle` and then `cPickle.__version__`, what do you get ?

**Comment by yinkaola** [comment]
My version is also 1.71
