### ISSUE TITLE
Dimension mismatch error when isExvivo set to True

### ISSUE THREAD

**Issue by Textite** [daducci/AMICO#66]
Hello,

I am using the Python version of the AMICO toolbox to run NODDI on ex vivo images. When I set the isExvivo flag to True and try to perform the fitting step, I encounter the following error (in core.py): 

line 336, in fit
    MAPs[ix,iy,iz,:], DIRs[ix,iy,iz,:], x, A = self.model.fit( y, dirs.reshape(-1,3), self.KERNELS, self.get_config('solver_params') )
**ValueError: cannot copy sequence with size 4 to array axis with dimension 3** 

From my interpretation, 'MAPs' is being assigned a 4 element array when it's size for each slice is 3 dimensions. Upon looking a bit closer, in my case at least I think that this is due to the fact that for ex vivo, the extra 'dot' map is being output in models.py, giving 4 total outputs being returned to the fitting function:

```
if self.isExvivo:
            return [v, od, fISO, xx[-2]], dirs, x, A
```

Am I doing something wrong, or perhaps I don't have the correct version installed? 
If I am not interested in the 'dot' map for the time being and I delete the 4th element in the array in the above line to circumvent this error will this disrupt how the ex vivo model is implemented in the rest of the code?  

Thanks very much.

**Comment by davidrs06** [comment]
Hi Textite, thank you for reporting this.

How do you activate the isExvivo flag ?

The size of `MAPs` depends on the size of `ae.model.maps_name`, which automatically adapts to the value of the `isExvivo` flag when using the [`ae.model.set( self, dPar, dIso, IC_VFs, IC_ODs, isExvivo )`](https://github.com/daducci/AMICO/blob/master/amico/models.py#L483) function. You should either use this function when setting parameters of your model, or use the following if you really want to set things manually:
```
ae.model.isExvivo=True
ae.model.maps_name = [ 'ICVF', 'OD', 'ISOVF', 'dot' ]
ae.model.maps_descr = [ 'Intra-cellular volume fraction', 'Orientation dispersion', 'Isotropic volume fraction', 'Dot volume fraction' ]
```

Let me know if this helps.

Cheers,
David

**Comment by davidrs06** [comment]
As an example, if you want just to activate the isExvivo flag and keep all other settings unchanged, I would use:
```
ae.model.set( ae.model.dPar, ae.model.dIso, ae.model.IC_VFs, ae.model.IC_ODs, True ) 
```

**Comment by Textite** [comment]
Hi David, thank you for your swift reply.

I was activating the isExvivo flag just through "ae.model.isExvivo = True". Upon manually entering:
```
ae.model.isExvivo=True
ae.model.maps_name = [ 'ICVF', 'OD', 'ISOVF', 'dot' ]
ae.model.maps_descr = [ 'Intra-cellular volume fraction', 'Orientation dispersion', 'Isotropic volume fraction', 'Dot volume fraction' ]
```
as per your suggestion, I was able to process and output all maps successfully without errors. I guess it wasn't including the dot volume fraction map in 'maps_name' and 'maps_descr' before with just the one line isExvivo activation? In any case thank you very much.

**Comment by davidrs06** [comment]
That's right, the function ae.model.set() takes care of activating/de-activating the isExvivo parameter and adapts the map names and descriptions accordingly.

Good to ear it works now. Let us know if you run into other issues.

Best regards,
David
