### ISSUE TITLE
Problem importing AMICO - No module named 'core'

### ISSUE THREAD

**Issue by dilaraerisen** [daducci/AMICO#68]
Hi,

I got this error after trying to import AMICO:

```
dilara@dilara-500-250et:~$ python
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spams
>>> import amico
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dilara/anaconda3/lib/python3.6/site-packages/amico/__init__.py", line 1, in <module>
    from core import Evaluation
ModuleNotFoundError: No module named 'core'
```

I do not get any errors during installation.

```
dilara@dilara-500-250et:~/AMICO-master$ pip install .
Processing /home/dilara/AMICO-master
Requirement already satisfied: dipy in /home/dilara/anaconda3/lib/python3.6/site-packages (from amico==1.0) (0.14.0)
Requirement already satisfied: nibabel>=2.1.0 in /home/dilara/anaconda3/lib/python3.6/site-packages (from dipy->amico==1.0) (2.3.0)
Requirement already satisfied: h5py>=2.4.0 in /home/dilara/anaconda3/lib/python3.6/site-packages (from dipy->amico==1.0) (2.7.0)
Requirement already satisfied: numpy>=1.7 in /home/dilara/anaconda3/lib/python3.6/site-packages (from h5py>=2.4.0->dipy->amico==1.0) (1.13.3)
Requirement already satisfied: six in /home/dilara/anaconda3/lib/python3.6/site-packages (from h5py>=2.4.0->dipy->amico==1.0) (1.11.0)
Building wheels for collected packages: amico
  Running setup.py bdist_wheel for amico ... done
  Stored in directory: /home/dilara/.cache/pip/wheels/d1/94/31/61888e4e578b43385618bb376053b2adb983ba5816227b51e9
Successfully built amico
Installing collected packages: amico
Successfully installed amico-1.0
```

SPAMS and Camino Toolkit seems to be working fine as far as I can tell. I am using Ubuntu 16.04 and Anaconda3-5.0.1. Can you tell what is wrong with my installation?

Best,
Dilara

**Comment by daducci** [comment]
Hi Dilara,

usually this error means that the compilation was unsuccessful, typically due to the external SPAMS module. Can you please check and test it works properly?

**Comment by dilaraerisen** [comment]
Hi,
I wasn't able to install SPAMS directly from pip repository in the first place so I've installed manually with:

wget https://gforge.inria.fr/frs/download.php/file/37660/spams-python.anaconda-v2.6.1-2018-08-06.tar.gz
tar -zxvf spams-python.anaconda-v2.6.1-2018-08-06.tar.gz
cd spams-2.6.1
python setup.py install

I don't know if it has something to do with the manual installation but I ran the tests located in "test" folder in my python install directory where the SPAMS is installed and they all worked out fine.

Best,
Dilara

**Comment by seantma** [comment]
I'm getting the same error that @dilaraerisen is experiencing. 

My SPAMS was installed through the `conda` package manager instead using the command below:
`conda install -c conda-forge python-spams` and it shows the install was successful.

Below is the version of `SPAM` that was installed:
-> % conda list python-spams
# packages in environment at /Users/tt/anaconda3:
#
# Name                    Version                   Build  Channel
python-spams              2.6.1           py36_blas_openblash6af021c_200  [blas_openblas]  conda-forge

 Any suggestions? 

Seab

**Comment by ptelyash** [comment]
Any solution to this? Have the same issue, with no installation errors (for all packages).
