### ISSUE TITLE
ICVF maxing at .990000000

### ISSUE THREAD

**Issue by bacaron** [daducci/AMICO#69]
Hello Dr. Daducci,

I'm attempting to use this toolbox to fit the NODDI model to a few different datasets. The speed of the processing as compared to the original matlab toolbox is incredible! I'm having a few issues with the outputs.

In every dataset I've used (including HCP), I'm getting max values for ICVF of 0.99000000537 (see attached image).

![screenshot from 2018-11-06 16-05-22](https://user-images.githubusercontent.com/22106265/48093596-c988ae00-e1dd-11e8-87a5-083c8fb1054f.png)

I'm using default settings for the NODDI model. I looked through the open and closed issues for anyone else who may have had this issue, and the only potential solution I saw was making sure the bvalues are in the proper scale (i.e. s/mm^2), which my bvalues are.

Any help with this issue would be greatly appreciated!

Thank you,
Brad Caron

**Comment by bacaron** [comment]
Update: I tested the NODDI sample dataset and obtained the same issue.

Is there an example output from the NODDI AMICO paper that I could use to validate?

Thanks,
Brad Caron

**Comment by daducci** [comment]
Hi @bacaron,
sorry for this long delay, I am ashamed of this, but I completely missed it. Did you solve your issue?

**Comment by bacaron** [comment]
Hi @daducci,

No worries at all! I probably have a log from at least a year ago of PRs to catch up on. Totally understand it slipping through the cracks.

I just noticed your response to another issue on the repo (https://github.com/daducci/AMICO/issues/97#issuecomment-624163268) which answers my question.

Thank you again for your response! I sincerely appreciate it!
Brad Caron
