### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by divetea** [daducci/AMICO#74]
Hi,
I am trying to run amico with python3 since we want to move all our software to this version soon.
Two problems that i found:
`"amico/preproc.py", line 37, debiasRician:   print without parenthesis`
and 

```
"amico/lut.py", line 73, in load_precomputed_rotation_matrices
    return pickle.load( open(filename,'rb') )

UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 1: ordinal not in range(128)
```
I have a working but ugly workaround for the second one:
```
if sys.version_info[0] == 3:
  aux = pickle.load( open(filename,'rb'), fix_imports=True, encoding='bytes' )
  result_aux = {k.decode(): v for k, v in aux.items()}
  return result_aux
else:
  return pickle.load( open(filename,'rb') )
```
I have to use sys.version_info because the python2 version of pickle does not know the argument fix_imports.

It would be nice if you could make the changes, if not i can make a pull request.
Cheers

**Comment by daducci** [comment]
Dear @divetea ,

thanks for pointing out this issue. At the moment we are short of people who could work on the project. It would be nice if you could prepare a PR to implement that. I'll merge it asap.

**Comment by ketograph** [comment]
I created a PR (#81) with the changed code.

**Comment by fullbat** [comment]
Hi,
I've found an issue related to the last PR (#81).
I get this error when trying to run COMMIT.

`
/home/.local/lib/python2.7/site-packages/amico/lut.pyc in load_precomputed_rotation_matrices(lmax)
     72         raise RuntimeError( 'Auxiliary matrices not found; call "lut.precompute_rotation_matrices()" first.' )
     73     with open( filename, 'rb' ) as rotation_matrices_file:
---> 74         if sys.version_info.major == 3:
     75             aux = pickle.load( rotation_matrices_file, fix_imports=True, encoding='bytes' )
     76             result_aux = {k.decode(): v for k, v in aux.items()}

NameError: global name 'sys' is not defined
`
