### ISSUE TITLE
Updates to ___version___ in the setup.py

### ISSUE THREAD

**Issue by trislett** [daducci/AMICO#77]
Could you please use versioning with your bug fixes and updates? AMICO is still listed as 1.0 despite many commits since I last used the software. It is important for citing AMICO in manuscripts as well as upgrading/maintaining with pip.

Thank you!

**Comment by daducci** [comment]
Dear @trislett ,

you're totally right, that would be helpful. We will pay more attention to versioning from now on.

Best,
Ale
