### ISSUE TITLE
development ceased?

### ISSUE THREAD

**Issue by cmeesters** [daducci/AMICO#78]
Dear Developers,

On behalf of one of our users I would like to ask:

- has the development ceased? (There are no recent commits and issues as well as PRs seem not to be addressed? )
- in order to support a given software on a cluster, there needs to be a release one can refer to (compare https://easybuild.readthedocs.io/en/latest/ ), would you be willing to either host amico at the Python Package index and/or create a github release?

Best regards,
Christian Meesters

**Comment by daducci** [comment]
Dear @cmeesters ,

Actually, the development is not ceased, not at all! There have been some changes lately in the team and we are short of people who actively work on it. Yet, I must also say, that we have been correcting bugs, when presented by the users, but the development is pretty stable as no new features were proposed.

Concerning your second question, I have to admit that I am not familiar with running software on a cluster. If you could help there, that would be great. On our side, there would be all the possible support to that process.
