### ISSUE TITLE
issue with spams installation

### ISSUE THREAD

**Issue by andebag** [daducci/AMICO#85]
Hi, I am new to coding / using python and I am having some issues installing SPAMS on my system. I have python 2.7.16, on windows. I was able to successfully install all the other packages, but I keep getting errors when I try to pip install spams. When I try to do:

pip install --index-url https://test.pypi.org/simple/ spams

I get:

Looking in indexes: https://test.pypi.org/simple/
Collecting spams
  Using cached https://test-files.pythonhosted.org/packages/4c/9f/710c1d07594ee434e5dd33632a07b62a1b5c25ad84e96c319dd498243fd7/spams-2.6.1.11.tar.gz
Requirement already satisfied: numpy in c:\python27\lib\site-packages (from spams) (1.16.4)
Requirement already satisfied: scipy in c:\python27\lib\site-packages (from spams) (1.2.1)
Requirement already satisfied: six in c:\python27\lib\site-packages (from spams) (1.12.0)
Installing collected packages: spams
  Running setup.py install for spams ... error
    ERROR: Complete output from command 'c:\python27\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'c:\\users\\andeba~1\\appdata\\local\\temp\\pip-install-jok3um\\spams\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\andeba~1\appdata\local\temp\pip-record-7slvfp\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    copying spams.py -> build\lib.win-amd64-2.7
    copying spams_wrap.py -> build\lib.win-amd64-2.7
    copying myscipy_rand.py -> build\lib.win-amd64-2.7
    running build_ext
    building '_spams_wrap' extension
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    C:\Users\Ande Bagdasarian\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I. -Ispams\linalg -Ispams\prox -Ispams\decomp -Ispams\dictLearn -Ic:\python27\lib\site-packages\numpy\core\include -Ic:\python27\include -Ic:\python27\include -Ic:\python27\include -Ic:\python27\PC /Tpspams_wrap.cpp /Fobuild\temp.win-amd64-2.7\Release\spams_wrap.obj -DNDEBUG -DUSE_BLAS_LIB -std=c++11 -fPIC -fopenmp -Wunused-variable -m64
    cl : Command line error D8021 : invalid numeric argument '/Wunused-variable'
    error: Command "C:\Users\Ande Bagdasarian\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I. -Ispams\linalg -Ispams\prox -Ispams\decomp -Ispams\dictLearn -Ic:\python27\lib\site-packages\numpy\core\include -Ic:\python27\include -Ic:\python27\include -Ic:\python27\include -Ic:\python27\PC /Tpspams_wrap.cpp /Fobuild\temp.win-amd64-2.7\Release\spams_wrap.obj -DNDEBUG -DUSE_BLAS_LIB -std=c++11 -fPIC -fopenmp -Wunused-variable -m64" failed with exit status 2
    ----------------------------------------
ERROR: Command "'c:\python27\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'c:\\users\\andeba~1\\appdata\\local\\temp\\pip-install-jok3um\\spams\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\andeba~1\appdata\local\temp\pip-record-7slvfp\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in c:\users\andeba~1\appdata\local\temp\pip-install-jok3um\spams\

Does this mean I have a problem with my C++ program? I installed it properly but I'm really not sure what the issue is... any ideas to point me in the right direction?

**Comment by daducci** [comment]
Hi @andebag ,

I have no experience with Windows, but it definitely an installation problem of the SPAMS library. Did you try checking on their website for help?

@fullbat, do you have any insight?

**Comment by andebag** [comment]
@daducci 
Thanks for the response. Yes their website doesn't seem to have info on this problem. I contacted the developers and am waiting for a response. I'm really stumped on this at the moment. If I can't figure it out I'm considering running a virtual machine with Ubuntu at trying it from there. Inconvenient, but an option I guess.

**Comment by fullbat** [comment]
Hi @andebag 
which C++ version are you using?

**Comment by andebag** [comment]
Hey @fullbat 
I originally was using the version offered for python 2.7 shown here 
https://www.microsoft.com/en-us/download/details.aspx?id=44266

I'll try installing VC++14, and let you know how that goes. Fingers crossed.

**Comment by andebag** [comment]
@fullbat @daducci 

Still not working. I might just uninstall everything and start over if it seems like things aren't communicating properly. What versions of everything do you recommend?

I saw on a forum that AMICO works best with python 2.7 so I used that.

Should I used the most up to date version of everything?

Or do you recommend I make a linux virtual machine and try there?

**Comment by fullbat** [comment]
@andebag 
I've just installed successfully the last version of AMICO with python 3.5 and the default g++ compiler on Ubuntu 16.04 LTS (unfortunately I don't have experience on Windows OS).
Maybe is good to start from a clean environment and I suggest to move to python 3.

**Comment by andebag** [comment]
@fullbat @daducci 

After a lot of troubleshooting and digging around I found this for AMICO installation for Windows using Anaconda:

https://gist.github.com/pangyuteng/5df295faf19d7474d3c3e86b90c2654a#file-readme-md

Just tested it and it produces identical results to running the pure NODDI matlab toolbox. I still don't understand why trying to use just python 2.7 on it's own would not work, but here we are. Thanks again for the help and suggestions guys!
