### ISSUE TITLE
error in exvivo NODDI fitting

### ISSUE THREAD

**Issue by lucilla7** [daducci/AMICO#88]
I'm processing a NODDI dataset with the following characteristics:

	* DWI signal...
		- dim    = 128 x 128 x 64 x 96
		- pixdim = 2.000 x 2.000 x 2.000
	* Acquisition scheme...
		- 96 samples, 2 shells
		- 12 @ b=0 , 20 @ b=1400.0 , 64 @ b=3000.0
	* Binary mask...
		- dim    = 128 x 128 x 64
		- pixdim = 2.000 x 2.000 x 2.000
		- voxels = 207975

with this code:

nd.set_model("NODDI")
nd.model.isExvivo = True
nd.model.dPar = 0.0006  # Sets the diffusivity of the model
nd.generate_kernels(regenerate=True)    # Make sure to regenerate the kernels
nd.load_kernels()
nd.fit()
nd.save_results()

and I get this error: 

Traceback (most recent call last):
  File "/Users/Apollo/PycharmProjects/NODDI_recon/exvivo_reco.py", line 323, in <module>
    nd.fit()
  File "/Users/Apollo/venv/lib/python2.7/site-packages/amico/core.py", line 327, in fit
    MAPs[ix,iy,iz,:], DIRs[ix,iy,iz,:], x, A = self.model.fit( y, dirs.reshape(-1,3), self.KERNELS, self.get_config('solver_params') )
ValueError: cannot copy sequence with size 4 to array axis with dimension 3

I am encountering this problem only in ex vivo. Should I install the newest version? I'm using amico 1.0

**Comment by daducci** [comment]
Hi @lucilla7 ,

what is the dimensionality of your mask? Can you plot the output of, for example, fslhd <FILENAME> or mrinfo <FILENAME>, for both the mask and the DWI dataset?

**Comment by lucilla7** [comment]
DWI dataset:

sizeof_hdr     348
data_type      FLOAT32
dim0           4
dim1           128
dim2           128
dim3           64
dim4           96
dim5           1
dim6           1
dim7           1
vox_units      Unknown
time_units     Unknown
datatype       16
nbyper         4
bitpix         32
pixdim0        0.000000
pixdim1        2.000000
pixdim2        2.000000
pixdim3        2.000000
pixdim4        1.000000
pixdim5        1.000000
pixdim6        1.000000
pixdim7        1.000000
vox_offset     352
cal_max        0.0000
cal_min        0.0000
scl_slope      1.000000
scl_inter      0.000000
phase_dim      0
freq_dim       0
slice_dim      0
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      0
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name    
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_name     Unknown
qform_code     0
qto_xyz:1      2.000000  0.000000  0.000000  0.000000
qto_xyz:2      0.000000  2.000000  0.000000  0.000000
qto_xyz:3      0.000000  0.000000  2.000000  0.000000
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
qform_xorient  Left-to-Right
qform_yorient  Posterior-to-Anterior
qform_zorient  Inferior-to-Superior
sform_name     Aligned Anat
sform_code     2
sto_xyz:1      -1.900521  -0.610190  0.125250  142.880081
sto_xyz:2      -0.609540  1.904618  0.029824  -105.633476
sto_xyz:3      0.128376  0.009832  1.995852  -62.487247
sto_xyz:4      0.000000  0.000000  0.000000  1.000000
sform_xorient  Right-to-Left
sform_yorient  Posterior-to-Anterior
sform_zorient  Inferior-to-Superior
file_type      NIFTI-1+
file_code      1
descrip        
aux_file  

Mask:

sizeof_hdr     348
data_type      FLOAT32
dim0           3
dim1           128
dim2           128
dim3           64
dim4           1
dim5           1
dim6           1
dim7           1
vox_units      Unknown
time_units     Unknown
datatype       16
nbyper         4
bitpix         32
pixdim0        0.000000
pixdim1        2.000000
pixdim2        2.000000
pixdim3        2.000000
pixdim4        1.000000
pixdim5        1.000000
pixdim6        1.000000
pixdim7        1.000000
vox_offset     352
cal_max        0.0000
cal_min        0.0000
scl_slope      1.000000
scl_inter      0.000000
phase_dim      0
freq_dim       0
slice_dim      0
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      0
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name    
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_name     Unknown
qform_code     0
qto_xyz:1      2.000000  0.000000  0.000000  0.000000
qto_xyz:2      0.000000  2.000000  0.000000  0.000000
qto_xyz:3      0.000000  0.000000  2.000000  0.000000
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
qform_xorient  Left-to-Right
qform_yorient  Posterior-to-Anterior
qform_zorient  Inferior-to-Superior
sform_name     Aligned Anat
sform_code     2
sto_xyz:1      -1.900521  -0.610190  0.125250  142.880081
sto_xyz:2      -0.609540  1.904618  0.029824  -105.633476
sto_xyz:3      0.128376  0.009832  1.995852  -62.487247
sto_xyz:4      0.000000  0.000000  0.000000  1.000000
sform_xorient  Right-to-Left
sform_yorient  Posterior-to-Anterior
sform_zorient  Inferior-to-Superior
file_type      NIFTI-1+
file_code      1
descrip        
aux_file

**Comment by daducci** [comment]
Your data looks fine, I don't see where the problem could be. Can you try updating AMICO to the latest version?

**Comment by RDadarwal** [comment]
Hi Alessandro Daducci,

I am also getting the same error with the latest version of AMICO. 

Thanks
Rakshit
