### ISSUE TITLE
.99 mask for ICVF.nii.gz files

### ISSUE THREAD

**Issue by CallowBrainProject** [daducci/AMICO#95]
Hello,

Many of my subjects appear to have values of .99 on the edges of the ICVF scans. And unfortunately, some of the subjects appear to have a mask where all of the voxels inside the b0 mask have a value=.99

However, the ODI and ISO images appear to be fine?

Any thoughts why this might be occurring
![Capture](https://user-images.githubusercontent.com/33704076/77851794-fbbaf700-71a8-11ea-9e98-4cd3afbae138.PNG)
![Capture1](https://user-images.githubusercontent.com/33704076/77851795-fc538d80-71a8-11ea-829c-5b16ea4991fc.PNG)
![Capture2](https://user-images.githubusercontent.com/33704076/77851796-fc538d80-71a8-11ea-938b-c6ac63fc4d21.PNG)

?

**Comment by daducci** [comment]
Hi @CallowBrainProject ,

is your issue similar to this (#28)? What is your scheme file?

**Comment by CallowBrainProject** [comment]
I just looked through Issue #28. As far as I can tell it isn't the same issue, however, the issue seems to be somewhat similar. For reference, I am running this on HCP data.


My bval.scheme file looks like this for the first subject where things appeared to work (although they did have .99's in areas that overlapped with CSF from ISOVF.

VERSION: BVECTOR
0.519218        -0.678098	0.520187        0.000000
0.940461        -0.284911	-0.185364	1000.000000
0.332740        0.874787        0.352182        2000.000000
0.062696        -0.395116	0.916489        3000.000000
0.195299        0.895544        -0.399822	1000.000000
0.469331        -0.795541	-0.383201	3000.000000
0.702082        -0.474367	0.531089        2000.000000
0.277576        0.337181        0.899589        1000.000000
-0.636052	-0.084263	0.767032        2000.000000
0.882737        0.450147        0.134699        3000.000000
0.224295        -0.886244	-0.405294	1000.000000
0.201882        0.125660        0.971315        2000.000000
0.843525        -0.420447	0.334199        3000.000000
-0.448841	-0.255421	0.856330        1000.000000
0.972035        0.234314        -0.015665	2000.000000
0.273082        0.950462        -0.148486	3000.000000
-0.517173	0.683569        -0.515039	0.000000
0.874913        0.329195        0.355188        1000.000000
-0.462356	0.875544        0.140178        2000.000000
-0.041258	-0.421210	-0.906024	3000.000000
-0.785634	-0.078043	0.613749        3000.000000
0.527427        -0.569808	0.630189        1000.000000

and for one of the subjects that didn't work, (as in the whole ICVF image is .99 as in the image above) this is the scheme.

VERSION: BVECTOR
0.567598        -0.679099       0.465465        0.000000
0.803533        0.413192        0.428496        3000.000000
0.405232        -0.883131       -0.236360       1000.000000
0.942710        0.219875        0.250905        2000.000000
0.544728        -0.615211       -0.569901       2000.000000
0.044780        0.436355        -0.898660       1000.000000
0.794896        0.594353        -0.122004       2000.000000
0.242976        0.923105        0.298062        3000.000000
0.351084        -0.569923       -0.742918       1000.000000
0.210134        -0.323293       0.922673        2000.000000
0.949153        -0.286452       -0.130593       3000.000000
0.398707        0.840192        -0.367574       1000.000000
0.008287        -0.952070       -0.305770       2000.000000
0.026795        -0.195886       0.980261        3000.000000
0.992415        -0.115615       0.041789        1000.000000
0.428337        -0.063379       -0.901394       2000.000000
0.916662        0.172715        -0.360417       3000.000000
0.567376        -0.680419       0.463805        0.000000

**The code I ran**
python <<EOF
import amico
import spams
amico.core.setup()

ae = amico.Evaluation("/data/bswift-1/dcallow/CONNECTOME/dwi/", "${subj}/T1w/Diffusion")
amico.util.fsl2scheme("/data/bswift-1/dcallow/CONNECTOME/dwi/${subj}/T1w/Diffusion/bvals","/data/bswift-1/dcallow/CONNECTOME/dwi/${subj}/T1w/Diffusion/bvecs",bStep=(0,1000,2000,300$
ae.load_data(dwi_filename = "data.nii.gz", scheme_filename = "bvals.scheme", mask_filename ="nodif_brain_mask.nii.gz", b0_thr = 5)
ae.set_model("NODDI")
ae.generate_kernels()
ae.load_kernels()
ae.fit()
ae.save_results()

EOF


**Output while running**

-> Setting b-values to the closest shell in [   0. 1000. 2000. 3000.]
-> Writing scheme file to [ /data/bswift-1/dcallow/CONNECTOME/dwi/620434/T1w/Diffusion/bvals.scheme ]

-> Loading data:
        * DWI signal...
                - dim    = 145 x 174 x 145 x 193
                - pixdim = 1.250 x 1.250 x 1.250
        * Acquisition scheme...
                - 193 samples, 3 shells
                - 12 @ b=0 , 60 @ b=3000.0 , 60 @ b=1000.0 , 61 @ b=2000.0
        * Binary mask...
                - dim    = 145 x 174 x 145
                - pixdim = 1.250 x 1.250 x 1.250
                - voxels = 783411

-> Preprocessing:
        * Normalizing to b0... [ min=0.00,  mean=0.17, max=13973.44 ]
        * Keeping all b0 volume(s)...
        [ 208.8 seconds ]

-> Creating LUT for "NODDI" model:
   [ LUT already computed. Call "generate_kernels( regenerate=True )" to force regeneration. ]

-> Resampling LUT for subject "620434/T1w/Diffusion":
^M                                                              ^M    [ 243.1 seconds ]

-> Fitting "NODDI" model to 783411 voxels:
^M                                                              ^M    [ 00h 48m 46s ]
-> Saving output to "AMICO/NODDI/*":
        - configuration  [OK]
        - FIT_dir.nii.gz  [OK]
        - FIT_ICVF.nii.gz  [OK]
        - FIT_OD.nii.gz  [OK]
        - FIT_ISOVF.nii.gz  [OK]
   [ DONE ]

**Comment by daducci** [comment]
I see that your first scheme is different from the second one, e.g., 2nd row of the first one is b=1000 while the second one is b=3000. Why the gradients are scrambled? AMICO assumes that the scheme is "the same" among subjects, meaning the same acquisition protocol has been used and the volumes in each NIFTI file correspond to the same gradients. Of course, the orientations can slightly change between subjects, but the scheme no (meaning the order of the b-values volumes in the file). Is this your problem?

**Comment by CallowBrainProject** [comment]
Yes, it appears that a few of the HCP subjects have bval schemes that are different than most. I assume there is nothing I can do to solve this issue? It does appear that these few subjects do have the same bval schemes.

**Comment by daducci** [comment]
As AMICO assumes the same protocol is shared by all subjects, unfortunately this assumption breaks here. A workaround is to regenerate the kernels for each subject using `generate_kernels( regenerate=True )` but this would slow down the processing a bit. Could this solve your issue? You could also divide the subjects into two groups: those for which you know the protocol is the same (and for these no need to regenerate the kernels each time) and those for which kernels need to be regenerated each time.

**Comment by CallowBrainProject** [comment]
I can completely understand why this is an issue. The good news is I have only identified a few subjects with the different scheme. I am going to try the second solution! I am curious though, if I run AMICO in parallel, can I still use the regenerate=True option? It seems like the kernel is regenerated in the same place for each subject and that this may just cause the kernels to be continuously modified so that it is never available to fit the model and thus crashes the fitting?

**Comment by daducci** [comment]
I think you should at least treat each subject as being part of an independent study, this way the kernels will be generated inside each subject's folder and are independent. To achieve this, you can e.g. move inside one subject's folder and load the data using `load_data('.', '.')`; dows this work for you? Not sure, sorry, but I never tested running different processing in parallel
